/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './speaker-detail';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/navigation/nav-params';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import18 from 'ionic-angular/config/config';
import * as import19 from '@angular/core/src/linker/element_ref';
import * as import20 from 'ionic-angular/navigation/view-controller';
import * as import21 from 'ionic-angular/components/app/app';
import * as import22 from 'ionic-angular/components/toolbar/toolbar';
import * as import23 from 'ionic-angular/util/keyboard';
import * as import24 from '@angular/core/src/zone/ng_zone';
import * as import25 from 'ionic-angular/components/tabs/tabs';
import * as import26 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import27 from 'ionic-angular/components/navbar/navbar';
import * as import28 from 'ionic-angular/components/icon/icon';
import * as import29 from 'ionic-angular/components/button/button';
import * as import30 from 'ionic-angular/components/content/content';
import * as import31 from '@angular/core/src/security';
export class Wrapper_SpeakerDetailPage {
  context:import0.SpeakerDetailPage;
  changed:boolean;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this.context = new import0.SpeakerDetailPage(p0,p1);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_SpeakerDetailPage_Host:import2.RenderComponentType = (null as any);
class _View_SpeakerDetailPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _SpeakerDetailPage_0_4:Wrapper_SpeakerDetailPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SpeakerDetailPage_Host0,renderType_SpeakerDetailPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-speaker-detail',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SpeakerDetailPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SpeakerDetailPage_0_4 = new Wrapper_SpeakerDetailPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.NavParams));
    this._appEl_0.initComponent(this._SpeakerDetailPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._SpeakerDetailPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.SpeakerDetailPage) && (0 === requestNodeIndex))) { return this._SpeakerDetailPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._SpeakerDetailPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SpeakerDetailPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_SpeakerDetailPage_Host === (null as any))) { (renderType_SpeakerDetailPage_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_SpeakerDetailPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const SpeakerDetailPageNgFactory:import11.ComponentFactory<import0.SpeakerDetailPage> = new import11.ComponentFactory<import0.SpeakerDetailPage>('page-speaker-detail',viewFactory_SpeakerDetailPage_Host0,import0.SpeakerDetailPage);
const styles_SpeakerDetailPage:any[] = ([] as any[]);
var renderType_SpeakerDetailPage:import2.RenderComponentType = (null as any);
class _View_SpeakerDetailPage0 extends import1.AppView<import0.SpeakerDetailPage> {
  _el_0:any;
  _Header_0_3:import12.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import13.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _ToolbarTitle_4_4:import14.Wrapper_ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _Content_9_4:import15.Wrapper_Content;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  /*private*/ _appEl_16:import3.AppElement;
  _Button_16_4:import16.Wrapper_Button;
  _text_17:any;
  _el_18:any;
  _Icon_18_3:import17.Wrapper_Icon;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  /*private*/ _appEl_21:import3.AppElement;
  _Button_21_4:import16.Wrapper_Button;
  _text_22:any;
  _el_23:any;
  _Icon_23_3:import17.Wrapper_Icon;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  /*private*/ _appEl_26:import3.AppElement;
  _Button_26_4:import16.Wrapper_Button;
  _text_27:any;
  _el_28:any;
  _Icon_28_3:import17.Wrapper_Icon;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SpeakerDetailPage0,renderType_SpeakerDetailPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import12.Wrapper_Header(this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import20.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import13.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import13.Wrapper_Navbar(this.parentInjector.get(import21.App),this.parentInjector.get(import20.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import14.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import14.Wrapper_ToolbarTitle(this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import22.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'',(null as any));
    compView_4.create(this._ToolbarTitle_4_4.context,[([] as any[]).concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','speaker-detail');
    this.renderer.setElementAttribute(this._el_9,'padding','');
    this._appEl_9 = new import3.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import15.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import15.Wrapper_Content(this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import21.App),this.parentInjector.get(import23.Keyboard),this.parentInjector.get(import24.NgZone),this.parentInjector.get(import20.ViewController,(null as any)),this.parentInjector.get(import25.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_11,'text-center','');
    this._text_12 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'img',(null as any));
    this._el_14 = this.renderer.createElement(this._el_11,'br',(null as any));
    this._text_15 = this.renderer.createText(this._el_11,'\n\n    ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_11,'button',(null as any));
    this.renderer.setElementAttribute(this._el_16,'clear','');
    this.renderer.setElementAttribute(this._el_16,'color','twitter');
    this.renderer.setElementAttribute(this._el_16,'icon-only','');
    this.renderer.setElementAttribute(this._el_16,'ion-button','');
    this.renderer.setElementAttribute(this._el_16,'small','');
    this._appEl_16 = new import3.AppElement(16,11,this,this._el_16);
    var compView_16:any = import16.viewFactory_Button0(this.viewUtils,this.injector(16),this._appEl_16);
    this._Button_16_4 = new import16.Wrapper_Button((null as any),'',this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_16),this.renderer);
    this._appEl_16.initComponent(this._Button_16_4.context,([] as any[]),compView_16);
    this._text_17 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_18 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_18,'name','logo-twitter');
    this.renderer.setElementAttribute(this._el_18,'role','img');
    this._Icon_18_3 = new import17.Wrapper_Icon(this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_18),this.renderer);
    this._text_19 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_16.create(this._Button_16_4.context,[([] as any[]).concat([
        this._text_17,
        this._el_18,
        this._text_19
      ]
    )],(null as any));
    this._text_20 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_11,'button',(null as any));
    this.renderer.setElementAttribute(this._el_21,'clear','');
    this.renderer.setElementAttribute(this._el_21,'color','github');
    this.renderer.setElementAttribute(this._el_21,'icon-only','');
    this.renderer.setElementAttribute(this._el_21,'ion-button','');
    this.renderer.setElementAttribute(this._el_21,'small','');
    this._appEl_21 = new import3.AppElement(21,11,this,this._el_21);
    var compView_21:any = import16.viewFactory_Button0(this.viewUtils,this.injector(21),this._appEl_21);
    this._Button_21_4 = new import16.Wrapper_Button((null as any),'',this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_21),this.renderer);
    this._appEl_21.initComponent(this._Button_21_4.context,([] as any[]),compView_21);
    this._text_22 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_23 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_23,'name','logo-github');
    this.renderer.setElementAttribute(this._el_23,'role','img');
    this._Icon_23_3 = new import17.Wrapper_Icon(this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_23),this.renderer);
    this._text_24 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_21.create(this._Button_21_4.context,[([] as any[]).concat([
        this._text_22,
        this._el_23,
        this._text_24
      ]
    )],(null as any));
    this._text_25 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_11,'button',(null as any));
    this.renderer.setElementAttribute(this._el_26,'clear','');
    this.renderer.setElementAttribute(this._el_26,'color','instagram');
    this.renderer.setElementAttribute(this._el_26,'icon-only','');
    this.renderer.setElementAttribute(this._el_26,'ion-button','');
    this.renderer.setElementAttribute(this._el_26,'small','');
    this._appEl_26 = new import3.AppElement(26,11,this,this._el_26);
    var compView_26:any = import16.viewFactory_Button0(this.viewUtils,this.injector(26),this._appEl_26);
    this._Button_26_4 = new import16.Wrapper_Button((null as any),'',this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_26),this.renderer);
    this._appEl_26.initComponent(this._Button_26_4.context,([] as any[]),compView_26);
    this._text_27 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_28 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_28,'name','logo-instagram');
    this.renderer.setElementAttribute(this._el_28,'role','img');
    this._Icon_28_3 = new import17.Wrapper_Icon(this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_28),this.renderer);
    this._text_29 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_26.create(this._Button_26_4.context,[([] as any[]).concat([
        this._text_27,
        this._el_28,
        this._text_29
      ]
    )],(null as any));
    this._text_30 = this.renderer.createText(this._el_11,'\n  ',(null as any));
    this._text_31 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_32 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'',(null as any));
    this._text_34 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_9.create(this._Content_9_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_10,
        this._el_11,
        this._text_31,
        this._el_32,
        this._text_34
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_35 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._text_35
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import26.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4.context; }
    if (((token === import27.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4.context; }
    if (((token === import22.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3.context; }
    if (((token === import28.Icon) && (18 === requestNodeIndex))) { return this._Icon_18_3.context; }
    if (((token === import29.Button) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._Button_16_4.context; }
    if (((token === import28.Icon) && (23 === requestNodeIndex))) { return this._Icon_23_3.context; }
    if (((token === import29.Button) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._Button_21_4.context; }
    if (((token === import28.Icon) && (28 === requestNodeIndex))) { return this._Icon_28_3.context; }
    if (((token === import29.Button) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._Button_26_4.context; }
    if (((token === import30.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._Content_9_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._ToolbarTitle_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    if (this._Content_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    const currVal_6:any = '';
    this._Button_16_4.check_small(currVal_6,throwOnChange,false);
    const currVal_7:any = '';
    this._Button_16_4.check_clear(currVal_7,throwOnChange,false);
    const currVal_8:any = 'twitter';
    this._Button_16_4.check_color(currVal_8,throwOnChange,false);
    if (this._Button_16_4.detectChangesInternal(this,this._el_16,throwOnChange)) { this._appEl_16.componentView.markAsCheckOnce(); }
    const currVal_9:any = 'logo-twitter';
    this._Icon_18_3.check_name(currVal_9,throwOnChange,false);
    this._Icon_18_3.detectChangesInternal(this,this._el_18,throwOnChange);
    const currVal_11:any = '';
    this._Button_21_4.check_small(currVal_11,throwOnChange,false);
    const currVal_12:any = '';
    this._Button_21_4.check_clear(currVal_12,throwOnChange,false);
    const currVal_13:any = 'github';
    this._Button_21_4.check_color(currVal_13,throwOnChange,false);
    if (this._Button_21_4.detectChangesInternal(this,this._el_21,throwOnChange)) { this._appEl_21.componentView.markAsCheckOnce(); }
    const currVal_14:any = 'logo-github';
    this._Icon_23_3.check_name(currVal_14,throwOnChange,false);
    this._Icon_23_3.detectChangesInternal(this,this._el_23,throwOnChange);
    const currVal_16:any = '';
    this._Button_26_4.check_small(currVal_16,throwOnChange,false);
    const currVal_17:any = '';
    this._Button_26_4.check_clear(currVal_17,throwOnChange,false);
    const currVal_18:any = 'instagram';
    this._Button_26_4.check_color(currVal_18,throwOnChange,false);
    if (this._Button_26_4.detectChangesInternal(this,this._el_26,throwOnChange)) { this._appEl_26.componentView.markAsCheckOnce(); }
    const currVal_19:any = 'logo-instagram';
    this._Icon_28_3.check_name(currVal_19,throwOnChange,false);
    this._Icon_28_3.detectChangesInternal(this,this._el_28,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Button_16_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_21_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_26_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'',this.context.speaker.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_5,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Content_9_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this.context.speaker.profilePic;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_13,'src',this.viewUtils.sanitizer.sanitize(import31.SecurityContext.URL,currVal_4));
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this.context.speaker.name;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_13,'alt',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_10:any = this._Icon_18_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_18,'hide',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_15:any = this._Icon_23_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_23,'hide',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_20:any = this._Icon_28_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_28,'hide',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = import4.interpolate(1,'',this.context.speaker.about,'');
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setText(this._text_33,currVal_21);
      this._expr_21 = currVal_21;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_18_3.context.ngOnDestroy();
    this._Icon_23_3.context.ngOnDestroy();
    this._Icon_28_3.context.ngOnDestroy();
    this._Content_9_4.context.ngOnDestroy();
  }
}
export function viewFactory_SpeakerDetailPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.SpeakerDetailPage> {
  if ((renderType_SpeakerDetailPage === (null as any))) { (renderType_SpeakerDetailPage = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,styles_SpeakerDetailPage,{})); }
  return new _View_SpeakerDetailPage0(viewUtils,parentInjector,declarationEl);
}