/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
import * as import0 from './schedule';
import * as import1 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import15 from '@angular/core/src/linker/component_factory';
export declare class Wrapper_SchedulePage {
    context: import0.SchedulePage;
    changed: boolean;
    constructor(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any);
    detectChangesInternal(view: import1.AppView<any>, el: any, throwOnChange: boolean): boolean;
}
export declare const SchedulePageNgFactory: import15.ComponentFactory<import0.SchedulePage>;
export declare function viewFactory_SchedulePage0(viewUtils: import4.ViewUtils, parentInjector: import5.Injector, declarationEl: import3.AppElement): import1.AppView<import0.SchedulePage>;
