/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './schedule';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/components/alert/alert';
import * as import9 from 'ionic-angular/components/app/app';
import * as import10 from 'ionic-angular/components/modal/modal';
import * as import11 from 'ionic-angular/navigation/nav-controller';
import * as import12 from '../../providers/conference-data';
import * as import13 from '../../providers/user-data';
import * as import14 from '@angular/core/src/metadata/view';
import * as import15 from '@angular/core/src/linker/component_factory';
import * as import16 from '@angular/core/src/linker/query_list';
import * as import17 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/menu/menu-toggle.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import22 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import23 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import24 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import25 from '../../node_modules/ionic-angular/components/segment/segment.ngfactory';
import * as import26 from '../../node_modules/ionic-angular/components/searchbar/searchbar.ngfactory';
import * as import27 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import28 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import29 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import30 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import31 from '../../node_modules/ionic-angular/components/list/list-header.ngfactory';
import * as import32 from '@angular/common/src/pipes/lowercase_pipe';
import * as import33 from 'ionic-angular/config/config';
import * as import34 from '@angular/core/src/linker/element_ref';
import * as import35 from 'ionic-angular/navigation/view-controller';
import * as import36 from 'ionic-angular/components/menu/menu-controller';
import * as import37 from 'ionic-angular/components/toolbar/toolbar';
import * as import38 from 'ionic-angular/util/keyboard';
import * as import39 from '@angular/core/src/zone/ng_zone';
import * as import40 from 'ionic-angular/components/tabs/tabs';
import * as import41 from 'ionic-angular/gestures/gesture-controller';
import * as import42 from '@angular/core/src/linker/template_ref';
import * as import43 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import44 from 'ionic-angular/util/form';
import * as import45 from 'ionic-angular/components/icon/icon';
import * as import46 from 'ionic-angular/components/button/button';
import * as import47 from 'ionic-angular/components/menu/menu-toggle';
import * as import48 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import49 from '@angular/forms/src/directives/ng_model';
import * as import50 from '@angular/forms/src/directives/ng_control';
import * as import51 from '@angular/forms/src/directives/ng_control_status';
import * as import52 from 'ionic-angular/components/searchbar/searchbar';
import * as import53 from 'ionic-angular/components/segment/segment';
import * as import54 from 'ionic-angular/components/navbar/navbar';
import * as import55 from '@angular/common/src/directives/ng_for';
import * as import56 from 'ionic-angular/components/list/list';
import * as import57 from 'ionic-angular/components/item/item';
import * as import58 from 'ionic-angular/components/list/list-header';
import * as import59 from 'ionic-angular/components/content/content';
import * as import60 from '../../node_modules/ionic-angular/components/label/label.ngfactory';
import * as import61 from 'ionic-angular/components/label/label';
import * as import62 from '../../node_modules/ionic-angular/components/item/item-sliding.ngfactory';
import * as import63 from 'ionic-angular/components/item/item-sliding';
export class Wrapper_SchedulePage {
  context:import0.SchedulePage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any,p5:any) {
    this.changed = false;
    this.context = new import0.SchedulePage(p0,p1,p2,p3,p4,p5);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_SchedulePage_Host:import2.RenderComponentType = (null as any);
class _View_SchedulePage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _SchedulePage_0_4:Wrapper_SchedulePage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SchedulePage_Host0,renderType_SchedulePage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-schedule',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SchedulePage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SchedulePage_0_4 = new Wrapper_SchedulePage(this.parentInjector.get(import8.AlertController),this.parentInjector.get(import9.App),this.parentInjector.get(import10.ModalController),this.parentInjector.get(import11.NavController),this.parentInjector.get(import12.ConferenceData),this.parentInjector.get(import13.UserData));
    this._appEl_0.initComponent(this._SchedulePage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._SchedulePage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.SchedulePage) && (0 === requestNodeIndex))) { return this._SchedulePage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._SchedulePage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._SchedulePage_0_4.context.ngAfterViewInit(); } }
  }
}
function viewFactory_SchedulePage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_SchedulePage_Host === (null as any))) { (renderType_SchedulePage_Host = viewUtils.createRenderComponentType('',0,import14.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_SchedulePage_Host0(viewUtils,parentInjector,declarationEl);
}
export const SchedulePageNgFactory:import15.ComponentFactory<import0.SchedulePage> = new import15.ComponentFactory<import0.SchedulePage>('page-schedule',viewFactory_SchedulePage_Host0,import0.SchedulePage);
const styles_SchedulePage:any[] = ([] as any[]);
var renderType_SchedulePage:import2.RenderComponentType = (null as any);
class _View_SchedulePage0 extends import1.AppView<import0.SchedulePage> {
  _viewQuery_scheduleList_0:import16.QueryList<any>;
  _el_0:any;
  _Header_0_3:import17.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import18.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _Button_4_4:import19.Wrapper_Button;
  _MenuToggle_4_5:import20.Wrapper_MenuToggle;
  _ToolbarItem_4_6:import21.Wrapper_ToolbarItem;
  _query_Button_4_0:import16.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import22.Wrapper_Icon;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _NgModel_9_3:import23.Wrapper_NgModel;
  _NgControl_9_4:any;
  _NgControlStatus_9_5:import24.Wrapper_NgControlStatus;
  _Segment_9_6:import25.Wrapper_Segment;
  _query_SegmentButton_9_0:import16.QueryList<any>;
  _text_10:any;
  _el_11:any;
  /*private*/ _appEl_11:import3.AppElement;
  _NgModel_11_4:import23.Wrapper_NgModel;
  _NgControl_11_5:any;
  _NgControlStatus_11_6:import24.Wrapper_NgControlStatus;
  _Searchbar_11_7:import26.Wrapper_Searchbar;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  /*private*/ _appEl_17:import3.AppElement;
  _Content_17_4:import27.Wrapper_Content;
  _text_18:any;
  _el_19:any;
  _List_19_3:import28.Wrapper_List;
  _text_20:any;
  _anchor_21:any;
  /*private*/ _appEl_21:import3.AppElement;
  _TemplateRef_21_5:any;
  _NgFor_21_6:import29.Wrapper_NgFor;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  /*private*/ _appEl_24:import3.AppElement;
  _Item_24_4:import30.Wrapper_Item;
  _ListHeader_24_5:import31.Wrapper_ListHeader;
  _query_Label_24_0:import16.QueryList<any>;
  _query_Button_24_1:import16.QueryList<any>;
  _query_Icon_24_2:import16.QueryList<any>;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  _pipe_lowercase_0:import32.LowerCasePipe;
  /*private*/ _expr_36:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SchedulePage0,renderType_SchedulePage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_scheduleList_0 = new import16.QueryList<any>();
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import17.Wrapper_Header(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import35.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this.renderer.setElementAttribute(this._el_2,'no-border-bottom','');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import18.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import18.Wrapper_Navbar(this.parentInjector.get(import9.App),this.parentInjector.get(import35.ViewController,(null as any)),this.parentInjector.get(import11.NavController,(null as any)),this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'ion-button','');
    this.renderer.setElementAttribute(this._el_4,'menuToggle','');
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import19.viewFactory_Button0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Button_4_4 = new import19.Wrapper_Button('','',this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_4),this.renderer);
    this._MenuToggle_4_5 = new import20.Wrapper_MenuToggle(this.parentInjector.get(import36.MenuController),new import34.ElementRef(this._el_4),this.parentInjector.get(import35.ViewController,(null as any)),this._Navbar_2_4.context);
    this._ToolbarItem_4_6 = new import21.Wrapper_ToolbarItem(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import37.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._query_Button_4_0 = new import16.QueryList<any>();
    this._appEl_4.initComponent(this._Button_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'name','menu');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._Icon_6_3 = new import22.Wrapper_Icon(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_4.create(this._Button_4_4.context,[([] as any[]).concat([
        this._text_5,
        this._el_6,
        this._text_7
      ]
    )],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-segment',(null as any));
    this._NgModel_9_3 = new import23.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_9_4 = this._NgModel_9_3.context;
    this._NgControlStatus_9_5 = new import24.Wrapper_NgControlStatus(this._NgControl_9_4);
    this._Segment_9_6 = new import25.Wrapper_Segment(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_9),this.renderer,this._NgControl_9_4);
    this._query_SegmentButton_9_0 = new import16.QueryList<any>();
    this._text_10 = this.renderer.createText(this._el_9,'\n     ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_9,'ion-searchbar',(null as any));
    this.renderer.setElementAttribute(this._el_11,'color','primary');
    this.renderer.setElementAttribute(this._el_11,'placeholder','Search');
    this._appEl_11 = new import3.AppElement(11,9,this,this._el_11);
    var compView_11:any = import26.viewFactory_Searchbar0(this.viewUtils,this.injector(11),this._appEl_11);
    this._NgModel_11_4 = new import23.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_11_5 = this._NgModel_11_4.context;
    this._NgControlStatus_11_6 = new import24.Wrapper_NgControlStatus(this._NgControl_11_5);
    this._Searchbar_11_7 = new import26.Wrapper_Searchbar(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_11),this.renderer,this._NgControl_11_5);
    this._appEl_11.initComponent(this._Searchbar_11_7.context,([] as any[]),compView_11);
    this._text_12 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_11.create(this._Searchbar_11_7.context,([] as any[]),(null as any));
    this._text_13 = this.renderer.createText(this._el_9,'\n    ',(null as any));
    this._text_14 = this.renderer.createText((null as any),'\n\n    \n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]).concat([this._el_4]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_14
      ]
      )
    ]
    ,(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n\n\n    \n',(null as any));
    this._text_16 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_17 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_17 = new import3.AppElement(17,(null as any),this,this._el_17);
    var compView_17:any = import27.viewFactory_Content0(this.viewUtils,this.injector(17),this._appEl_17);
    this._Content_17_4 = new import27.Wrapper_Content(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_17),this.renderer,this.parentInjector.get(import9.App),this.parentInjector.get(import38.Keyboard),this.parentInjector.get(import39.NgZone),this.parentInjector.get(import35.ViewController,(null as any)),this.parentInjector.get(import40.Tabs,(null as any)));
    this._appEl_17.initComponent(this._Content_17_4.context,([] as any[]),compView_17);
    this._text_18 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_19_3 = new import28.Wrapper_List(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_19),this.renderer,this.parentInjector.get(import41.GestureController));
    this._text_20 = this.renderer.createText(this._el_19,'\n\n    ',(null as any));
    this._anchor_21 = this.renderer.createTemplateAnchor(this._el_19,(null as any));
    this._appEl_21 = new import3.AppElement(21,19,this,this._anchor_21);
    this._TemplateRef_21_5 = new import42.TemplateRef_(this._appEl_21,viewFactory_SchedulePage1);
    this._NgFor_21_6 = new import29.Wrapper_NgFor(this._appEl_21.vcRef,this._TemplateRef_21_5,this.parentInjector.get(import43.IterableDiffers),this.ref);
    this._text_22 = this.renderer.createText(this._el_19,'\n\n  ',(null as any));
    this._text_23 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_24 = this.renderer.createElement((null as any),'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','item');
    this._appEl_24 = new import3.AppElement(24,17,this,this._el_24);
    var compView_24:any = import30.viewFactory_Item0(this.viewUtils,this.injector(24),this._appEl_24);
    this._Item_24_4 = new import30.Wrapper_Item(this.parentInjector.get(import44.Form),this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_24),this.renderer);
    this._ListHeader_24_5 = new import31.Wrapper_ListHeader(this.parentInjector.get(import33.Config),this.renderer,new import34.ElementRef(this._el_24),(null as any));
    this._query_Label_24_0 = new import16.QueryList<any>();
    this._query_Button_24_1 = new import16.QueryList<any>();
    this._query_Icon_24_2 = new import16.QueryList<any>();
    this._appEl_24.initComponent(this._Item_24_4.context,([] as any[]),compView_24);
    this._text_25 = this.renderer.createText((null as any),'\n      No Sessions Found\n  ',(null as any));
    this._query_Label_24_0.reset(([] as any[]));
    this._Item_24_4.context.contentLabel = this._query_Label_24_0.first;
    compView_24.create(this._Item_24_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_25]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_26 = this.renderer.createText((null as any),'\n\n\n',(null as any));
    compView_17.create(this._Content_17_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_18,
        this._el_19,
        this._text_23,
        this._el_24,
        this._text_26
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_27 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_9,'ngModelChange',this.eventHandler(this._handle_ngModelChange_9_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_9,'ionChange',this.eventHandler(this._handle_ionChange_9_1.bind(this)));
    const subscription_0:any = this._NgModel_9_3.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_9_0.bind(this)));
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    const subscription_1:any = this._Segment_9_6.context.ionChange.subscribe(this.eventHandler(this._handle_ionChange_9_1.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_11,'ngModelChange',this.eventHandler(this._handle_ngModelChange_11_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_11,'ionInput',this.eventHandler(this._handle_ionInput_11_1.bind(this)));
    const subscription_2:any = this._NgModel_11_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_11_0.bind(this)));
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    const subscription_3:any = this._Searchbar_11_7.context.ionInput.subscribe(this.eventHandler(this._handle_ionInput_11_1.bind(this)));
    this._expr_33 = import7.UNINITIALIZED;
    this._expr_34 = import7.UNINITIALIZED;
    this._pipe_lowercase_0 = new import32.LowerCasePipe();
    this._expr_36 = import7.UNINITIALIZED;
    this._viewQuery_scheduleList_0.reset([this._List_19_3.context]);
    this.context.scheduleList = this._viewQuery_scheduleList_0.first;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._anchor_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._text_27
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2,
      subscription_3
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import45.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3.context; }
    if (((token === import46.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_4_4.context; }
    if (((token === import47.MenuToggle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._MenuToggle_4_5.context; }
    if (((token === import48.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarItem_4_6.context; }
    if (((token === import49.NgModel) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._NgModel_11_4.context; }
    if (((token === import50.NgControl) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._NgControl_11_5; }
    if (((token === import51.NgControlStatus) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._NgControlStatus_11_6.context; }
    if (((token === import52.Searchbar) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Searchbar_11_7.context; }
    if (((token === import49.NgModel) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._NgModel_9_3.context; }
    if (((token === import50.NgControl) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._NgControl_9_4; }
    if (((token === import51.NgControlStatus) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._NgControlStatus_9_5.context; }
    if (((token === import53.Segment) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Segment_9_6.context; }
    if (((token === import54.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Navbar_2_4.context; }
    if (((token === import37.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._Header_0_3.context; }
    if (((token === import42.TemplateRef) && (21 === requestNodeIndex))) { return this._TemplateRef_21_5; }
    if (((token === import55.NgFor) && (21 === requestNodeIndex))) { return this._NgFor_21_6.context; }
    if (((token === import56.List) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._List_19_3.context; }
    if (((token === import57.Item) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._Item_24_4.context; }
    if (((token === import58.ListHeader) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._ListHeader_24_5.context; }
    if (((token === import59.Content) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Content_17_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._Button_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    const currVal_3:any = '';
    this._MenuToggle_4_5.check_menuToggle(currVal_3,throwOnChange,false);
    this._MenuToggle_4_5.detectChangesInternal(this,this._el_4,throwOnChange);
    this._ToolbarItem_4_6.detectChangesInternal(this,this._el_4,throwOnChange);
    const currVal_5:any = 'menu';
    this._Icon_6_3.check_name(currVal_5,throwOnChange,false);
    this._Icon_6_3.detectChangesInternal(this,this._el_6,throwOnChange);
    const currVal_9:any = this.context.segment;
    this._NgModel_9_3.check_model(currVal_9,throwOnChange,false);
    this._NgModel_9_3.detectChangesInternal(this,this._el_9,throwOnChange);
    this._NgControlStatus_9_5.detectChangesInternal(this,this._el_9,throwOnChange);
    this._Segment_9_6.detectChangesInternal(this,this._el_9,throwOnChange);
    const currVal_18:any = this.context.queryText;
    this._NgModel_11_4.check_model(currVal_18,throwOnChange,false);
    this._NgModel_11_4.detectChangesInternal(this,this._el_11,throwOnChange);
    this._NgControlStatus_11_6.detectChangesInternal(this,this._el_11,throwOnChange);
    const currVal_25:any = 'primary';
    this._Searchbar_11_7.check_color(currVal_25,throwOnChange,false);
    const currVal_26:any = 'Search';
    this._Searchbar_11_7.check_placeholder(currVal_26,throwOnChange,false);
    this._Searchbar_11_7.detectChangesInternal(this,this._el_11,throwOnChange);
    if (this._Content_17_4.detectChangesInternal(this,this._el_17,throwOnChange)) { this._appEl_17.componentView.markAsCheckOnce(); }
    this._List_19_3.detectChangesInternal(this,this._el_19,throwOnChange);
    const currVal_35:any = this.context.groups;
    this._NgFor_21_6.check_ngForOf(currVal_35,throwOnChange,false);
    this._NgFor_21_6.detectChangesInternal(this,this._anchor_21,throwOnChange);
    if (this._Item_24_4.detectChangesInternal(this,this._el_24,throwOnChange)) { this._appEl_24.componentView.markAsCheckOnce(); }
    this._ListHeader_24_5.detectChangesInternal(this,this._el_24,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_4_4.context]);
        this._ToolbarItem_4_6.context._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if (this._query_SegmentButton_9_0.dirty) {
        this._query_SegmentButton_9_0.reset(([] as any[]));
        this._Segment_9_6.context._buttons = this._query_SegmentButton_9_0;
        this._query_SegmentButton_9_0.notifyOnChanges();
      }
      if (this._query_Button_24_1.dirty) {
        this._query_Button_24_1.reset(([] as any[]));
        this._Item_24_4.context._buttons = this._query_Button_24_1;
        this._query_Button_24_1.notifyOnChanges();
      }
      if (this._query_Icon_24_2.dirty) {
        this._query_Icon_24_2.reset(([] as any[]));
        this._Item_24_4.context._icons = this._query_Icon_24_2;
        this._query_Icon_24_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_4_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Searchbar_11_7.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_24_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_4_5.context.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_4,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_6_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_10:any = this._NgControlStatus_9_5.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_9,'ng-untouched',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatus_9_5.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_9,'ng-touched',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatus_9_5.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_9,'ng-pristine',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatus_9_5.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_9,'ng-dirty',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._NgControlStatus_9_5.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_9,'ng-valid',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_9_5.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_9,'ng-invalid',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_19:any = this._NgControlStatus_11_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_11,'ng-untouched',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_11_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_11,'ng-touched',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatus_11_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_11,'ng-pristine',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = this._NgControlStatus_11_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_11,'ng-dirty',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this._NgControlStatus_11_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_11,'ng-valid',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this._NgControlStatus_11_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_11,'ng-invalid',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_27:any = this._Searchbar_11_7.context.animated;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_11,'searchbar-animated',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._Searchbar_11_7.context._value;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_11,'searchbar-has-value',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._Searchbar_11_7.context._isActive;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_11,'searchbar-active',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._Searchbar_11_7.context.showCancelButton;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_11,'searchbar-show-cancel',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = this._Searchbar_11_7.context._shouldAlignLeft;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_11,'searchbar-left-aligned',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._Searchbar_11_7.context._sbHasFocus;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_11,'searchbar-has-focus',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = this._Content_17_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementClass(this._el_17,'statusbar-padding',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_34:any = (this.context.shownSessions === 0);
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementProperty(this._el_19,'hidden',currVal_34);
      this._expr_34 = currVal_34;
    }
    const currVal_36:any = (this.context.shownSessions > 0);
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementProperty(this._el_24,'hidden',currVal_36);
      this._expr_36 = currVal_36;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Segment_9_6.context.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); }
    }
  }
  destroyInternal():void {
    this._Icon_6_3.context.ngOnDestroy();
    this._NgModel_11_4.context.ngOnDestroy();
    this._NgModel_9_3.context.ngOnDestroy();
    this._Content_17_4.context.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_4_5.context.toggle()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.segment = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionChange_9_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.updateSchedule()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.queryText = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionInput_11_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.updateSchedule()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_SchedulePage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.SchedulePage> {
  if ((renderType_SchedulePage === (null as any))) { (renderType_SchedulePage = viewUtils.createRenderComponentType('',0,import14.ViewEncapsulation.None,styles_SchedulePage,{})); }
  return new _View_SchedulePage0(viewUtils,parentInjector,declarationEl);
}
class _View_SchedulePage1 extends import1.AppView<any> {
  _el_0:any;
  _ItemGroup_0_3:import30.Wrapper_ItemGroup;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Item_2_4:import30.Wrapper_Item;
  _query_Label_2_0:import16.QueryList<any>;
  _query_Button_2_1:import16.QueryList<any>;
  _query_Icon_2_2:import16.QueryList<any>;
  _text_3:any;
  _el_4:any;
  _Label_4_3:import60.Wrapper_Label;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _anchor_11:any;
  /*private*/ _appEl_11:import3.AppElement;
  _TemplateRef_11_5:any;
  _NgFor_11_6:import29.Wrapper_NgFor;
  _text_12:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SchedulePage1,renderType_SchedulePage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item-group',(null as any));
    this._ItemGroup_0_3 = new import30.Wrapper_ItemGroup();
    this._text_1 = this.renderer.createText(this._el_0,'\n\n      ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-item-divider',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','item');
    this.renderer.setElementAttribute(this._el_2,'sticky','');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import30.viewFactory_Item0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Item_2_4 = new import30.Wrapper_Item(this.parent.parentInjector.get(import44.Form),this.parent.parentInjector.get(import33.Config),new import34.ElementRef(this._el_2),this.renderer);
    this._query_Label_2_0 = new import16.QueryList<any>();
    this._query_Button_2_1 = new import16.QueryList<any>();
    this._query_Icon_2_2 = new import16.QueryList<any>();
    this._appEl_2.initComponent(this._Item_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_4_3 = new import60.Wrapper_Label(this.parent.parentInjector.get(import33.Config),new import34.ElementRef(this._el_4),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n          ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'strong',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_2_0.reset([this._Label_4_3.context]);
    this._Item_2_4.context.contentLabel = this._query_Label_2_0.first;
    compView_2.create(this._Item_2_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_4]),
      ([] as any[]).concat([
        this._text_3,
        this._text_9
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n\n      ',(null as any));
    this._anchor_11 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_11 = new import3.AppElement(11,0,this,this._anchor_11);
    this._TemplateRef_11_5 = new import42.TemplateRef_(this._appEl_11,viewFactory_SchedulePage2);
    this._NgFor_11_6 = new import29.Wrapper_NgFor(this._appEl_11.vcRef,this._TemplateRef_11_5,this.parent.parentInjector.get(import43.IterableDiffers),this.parent.ref);
    this._text_12 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._anchor_11,
      this._text_12
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import61.Label) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Label_4_3.context; }
    if (((token === import57.Item) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Item_2_4.context; }
    if (((token === import42.TemplateRef) && (11 === requestNodeIndex))) { return this._TemplateRef_11_5; }
    if (((token === import55.NgFor) && (11 === requestNodeIndex))) { return this._NgFor_11_6.context; }
    if (((token === import57.ItemGroup) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._ItemGroup_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ItemGroup_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    if (this._Item_2_4.detectChangesInternal(this,this._el_2,throwOnChange)) { this._appEl_2.componentView.markAsCheckOnce(); }
    this._Label_4_3.detectChangesInternal(this,this._el_4,throwOnChange);
    const currVal_2:any = this.context.$implicit.sessions;
    this._NgFor_11_6.check_ngForOf(currVal_2,throwOnChange,false);
    this._NgFor_11_6.detectChangesInternal(this,this._anchor_11,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_2_1.dirty) {
        this._query_Button_2_1.reset(([] as any[]));
        this._Item_2_4.context._buttons = this._query_Button_2_1;
        this._query_Button_2_1.notifyOnChanges();
      }
      if (this._query_Icon_2_2.dirty) {
        this._query_Icon_2_2.reset(([] as any[]));
        this._Item_2_4.context._icons = this._query_Icon_2_2;
        this._query_Icon_2_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_2_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this.context.$implicit.hide;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_0,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'',this.context.$implicit.time,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_7,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SchedulePage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_SchedulePage1(viewUtils,parentInjector,declarationEl);
}
class _View_SchedulePage2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _ItemSliding_0_4:import62.Wrapper_ItemSliding;
  _query_Item_0_0:import16.QueryList<any>;
  _query_ItemOptions_0_1:import16.QueryList<any>;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Item_2_4:import30.Wrapper_Item;
  _ItemContent_2_5:import30.Wrapper_ItemContent;
  _query_Label_2_0:import16.QueryList<any>;
  _query_Button_2_1:import16.QueryList<any>;
  _query_Icon_2_2:import16.QueryList<any>;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _pipe_lowercase_0_0:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SchedulePage2,renderType_SchedulePage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item-sliding',(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import62.viewFactory_ItemSliding0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ItemSliding_0_4 = new import62.Wrapper_ItemSliding((<_View_SchedulePage0>this.parent.parent)._List_19_3.context,this.renderer,new import34.ElementRef(this._el_0),this.parent.parent.parentInjector.get(import39.NgZone));
    this._query_Item_0_0 = new import16.QueryList<any>();
    this._query_ItemOptions_0_1 = new import16.QueryList<any>();
    this._appEl_0.initComponent(this._ItemSliding_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n\n        ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','item item-block');
    this.renderer.setElementAttribute(this._el_2,'ion-item','');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import30.viewFactory_Item0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Item_2_4 = new import30.Wrapper_Item(this.parent.parent.parentInjector.get(import44.Form),this.parent.parent.parentInjector.get(import33.Config),new import34.ElementRef(this._el_2),this.renderer);
    this._ItemContent_2_5 = new import30.Wrapper_ItemContent();
    this._query_Label_2_0 = new import16.QueryList<any>();
    this._query_Button_2_1 = new import16.QueryList<any>();
    this._query_Icon_2_2 = new import16.QueryList<any>();
    this._appEl_2.initComponent(this._Item_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'h3',(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'',(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._query_Label_2_0.reset(([] as any[]));
    this._Item_2_4.context.contentLabel = this._query_Label_2_0.first;
    compView_2.create(this._Item_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_6,
        this._el_7,
        this._text_9
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_10 = this.renderer.createText((null as any),'\n\n\n      ',(null as any));
    this._query_Item_0_0.reset([this._Item_2_4.context]);
    this._ItemSliding_0_4.context.item = this._query_Item_0_0.first;
    compView_0.create(this._ItemSliding_0_4.context,[
      ([] as any[]).concat([this._el_2]),
      ([] as any[])
    ]
    ,(null as any));
    this._pipe_lowercase_0_0 = import4.pureProxy1((<_View_SchedulePage0>this.parent.parent)._pipe_lowercase_0.transform.bind((<_View_SchedulePage0>this.parent.parent)._pipe_lowercase_0));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._text_10
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import57.Item) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Item_2_4.context; }
    if (((token === import57.ItemContent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._ItemContent_2_5.context; }
    if (((token === import63.ItemSliding) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ItemSliding_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    if (this._ItemSliding_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    if (this._Item_2_4.detectChangesInternal(this,this._el_2,throwOnChange)) { this._appEl_2.componentView.markAsCheckOnce(); }
    this._ItemContent_2_5.detectChangesInternal(this,this._el_2,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_2_1.dirty) {
        this._query_Button_2_1.reset(([] as any[]));
        this._Item_2_4.context._buttons = this._query_Button_2_1;
        this._query_Button_2_1.notifyOnChanges();
      }
      if (this._query_Icon_2_2.dirty) {
        this._query_Icon_2_2.reset(([] as any[]));
        this._Item_2_4.context._icons = this._query_Icon_2_2;
        this._query_Icon_2_2.notifyOnChanges();
      }
      if (this._query_ItemOptions_0_1.dirty) {
        this._query_ItemOptions_0_1.reset(([] as any[]));
        this._ItemSliding_0_4.context._itemOptions = this._query_ItemOptions_0_1;
        this._query_ItemOptions_0_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_2_4.context.ngAfterContentInit(); }
    }
    valUnwrapper.reset();
    const currVal_0:any = valUnwrapper.unwrap(import4.castByValue(this._pipe_lowercase_0_0,(<_View_SchedulePage0>this.parent.parent)._pipe_lowercase_0.transform)(this.context.$implicit.tracks[0]));
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_0,currVal_0))) {
      this.renderer.setElementAttribute(this._el_0,'track',((currVal_0 == (null as any))? (null as any): currVal_0.toString()));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.context.$implicit.hide;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_0,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_3:any = import4.interpolate(1,'',this.context.$implicit.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_5,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import4.interpolate(3,'\n            ',this.context.$implicit.timeStart,' —\n            ',this.context.$implicit.timeEnd,':\n            ',this.context.$implicit.location,'\n          ');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_8,currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.goToSessionDetail(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_SchedulePage2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_SchedulePage2(viewUtils,parentInjector,declarationEl);
}