/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/util/events';
import * as import9 from '../providers/user-data';
import * as import10 from 'ionic-angular/components/menu/menu-controller';
import * as import11 from 'ionic-angular/platform/platform';
import * as import12 from '../providers/conference-data';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from '@angular/core/src/linker/query_list';
import * as import16 from '../node_modules/ionic-angular/components/menu/menu.ngfactory';
import * as import17 from '../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import18 from '../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import19 from '../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import20 from '../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import21 from '../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import22 from '../node_modules/ionic-angular/components/list/list-header.ngfactory';
import * as import23 from '../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import24 from '../node_modules/ionic-angular/components/nav/nav.ngfactory';
import * as import25 from '@angular/core/src/linker/element_ref';
import * as import26 from 'ionic-angular/config/config';
import * as import27 from 'ionic-angular/util/keyboard';
import * as import28 from '@angular/core/src/zone/ng_zone';
import * as import29 from 'ionic-angular/gestures/gesture-controller';
import * as import30 from 'ionic-angular/navigation/view-controller';
import * as import31 from 'ionic-angular/components/navbar/navbar';
import * as import32 from 'ionic-angular/components/app/app';
import * as import33 from 'ionic-angular/components/tabs/tabs';
import * as import34 from 'ionic-angular/util/form';
import * as import35 from '@angular/core/src/linker/template_ref';
import * as import36 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import37 from 'ionic-angular/navigation/nav-controller-base';
import * as import38 from '@angular/core/src/linker/component_factory_resolver';
import * as import39 from 'ionic-angular/transitions/transition-controller';
import * as import40 from 'ionic-angular/navigation/deep-linker';
import * as import41 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import42 from 'ionic-angular/components/toolbar/toolbar';
import * as import43 from 'ionic-angular/components/item/item';
import * as import44 from 'ionic-angular/components/list/list-header';
import * as import45 from '@angular/common/src/directives/ng_for';
import * as import46 from 'ionic-angular/components/list/list';
import * as import47 from 'ionic-angular/components/content/content';
import * as import48 from 'ionic-angular/components/menu/menu';
import * as import49 from 'ionic-angular/components/nav/nav';
import * as import50 from '../node_modules/ionic-angular/components/menu/menu-close.ngfactory';
import * as import51 from '../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import52 from 'ionic-angular/components/icon/icon';
import * as import53 from 'ionic-angular/components/menu/menu-close';
export class Wrapper_ConferenceApp {
  context:import0.ConferenceApp;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any) {
    this.changed = false;
    this.context = new import0.ConferenceApp(p0,p1,p2,p3,p4);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_ConferenceApp_Host:import2.RenderComponentType = (null as any);
class _View_ConferenceApp_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _ConferenceApp_0_4:Wrapper_ConferenceApp;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ConferenceApp_Host0,renderType_ConferenceApp_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ConferenceApp0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ConferenceApp_0_4 = new Wrapper_ConferenceApp(this.parentInjector.get(import8.Events),this.parentInjector.get(import9.UserData),this.parentInjector.get(import10.MenuController),this.parentInjector.get(import11.Platform),this.parentInjector.get(import12.ConferenceData));
    this._appEl_0.initComponent(this._ConferenceApp_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._ConferenceApp_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ConferenceApp) && (0 === requestNodeIndex))) { return this._ConferenceApp_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ConferenceApp_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ConferenceApp_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_ConferenceApp_Host === (null as any))) { (renderType_ConferenceApp_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ConferenceApp_Host0(viewUtils,parentInjector,declarationEl);
}
export const ConferenceAppNgFactory:import14.ComponentFactory<import0.ConferenceApp> = new import14.ComponentFactory<import0.ConferenceApp>('ng-component',viewFactory_ConferenceApp_Host0,import0.ConferenceApp);
const styles_ConferenceApp:any[] = ([] as any[]);
var renderType_ConferenceApp:import2.RenderComponentType = (null as any);
class _View_ConferenceApp0 extends import1.AppView<import0.ConferenceApp> {
  _viewQuery_Nav_0:import15.QueryList<any>;
  _text_0:any;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Menu_2_4:import16.Wrapper_Menu;
  _query_Content_2_0:import15.QueryList<any>;
  _text_3:any;
  _el_4:any;
  _Header_4_3:import17.Wrapper_Header;
  _text_5:any;
  _el_6:any;
  /*private*/ _appEl_6:import3.AppElement;
  _Toolbar_6_4:import17.Wrapper_Toolbar;
  _text_7:any;
  _el_8:any;
  /*private*/ _appEl_8:import3.AppElement;
  _ToolbarTitle_8_4:import18.Wrapper_ToolbarTitle;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  /*private*/ _appEl_13:import3.AppElement;
  _Content_13_4:import19.Wrapper_Content;
  _text_14:any;
  _el_15:any;
  _List_15_3:import20.Wrapper_List;
  _text_16:any;
  _el_17:any;
  /*private*/ _appEl_17:import3.AppElement;
  _Item_17_4:import21.Wrapper_Item;
  _ListHeader_17_5:import22.Wrapper_ListHeader;
  _query_Label_17_0:import15.QueryList<any>;
  _query_Button_17_1:import15.QueryList<any>;
  _query_Icon_17_2:import15.QueryList<any>;
  _text_18:any;
  _text_19:any;
  _anchor_20:any;
  /*private*/ _appEl_20:import3.AppElement;
  _TemplateRef_20_5:any;
  _NgFor_20_6:import23.Wrapper_NgFor;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  /*private*/ _appEl_26:import3.AppElement;
  _Menu_26_4:import16.Wrapper_Menu;
  _query_Content_26_0:import15.QueryList<any>;
  _text_27:any;
  _el_28:any;
  _Header_28_3:import17.Wrapper_Header;
  _text_29:any;
  _el_30:any;
  /*private*/ _appEl_30:import3.AppElement;
  _Toolbar_30_4:import17.Wrapper_Toolbar;
  _text_31:any;
  _el_32:any;
  /*private*/ _appEl_32:import3.AppElement;
  _ToolbarTitle_32_4:import18.Wrapper_ToolbarTitle;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  /*private*/ _appEl_37:import3.AppElement;
  _Content_37_4:import19.Wrapper_Content;
  _text_38:any;
  _el_39:any;
  _List_39_3:import20.Wrapper_List;
  _text_40:any;
  _el_41:any;
  /*private*/ _appEl_41:import3.AppElement;
  _Item_41_4:import21.Wrapper_Item;
  _ListHeader_41_5:import22.Wrapper_ListHeader;
  _query_Label_41_0:import15.QueryList<any>;
  _query_Button_41_1:import15.QueryList<any>;
  _query_Icon_41_2:import15.QueryList<any>;
  _text_42:any;
  _text_43:any;
  _anchor_44:any;
  /*private*/ _appEl_44:import3.AppElement;
  _TemplateRef_44_5:any;
  _NgFor_44_6:import23.Wrapper_NgFor;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  /*private*/ _appEl_50:import3.AppElement;
  _Nav_50_4:import24.Wrapper_Nav;
  _text_51:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ConferenceApp0,renderType_ConferenceApp,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_Nav_0 = new import15.QueryList<any>();
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_2 = this.renderer.createElement(parentRenderNode,'ion-menu',(null as any));
    this.renderer.setElementAttribute(this._el_2,'id','loggedOutMenu');
    this.renderer.setElementAttribute(this._el_2,'role','navigation');
    this._appEl_2 = new import3.AppElement(2,(null as any),this,this._el_2);
    var compView_2:any = import16.viewFactory_Menu0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Menu_2_4 = new import16.Wrapper_Menu(this.parentInjector.get(import10.MenuController),new import25.ElementRef(this._el_2),this.parentInjector.get(import26.Config),this.parentInjector.get(import11.Platform),this.renderer,this.parentInjector.get(import27.Keyboard),this.parentInjector.get(import28.NgZone),this.parentInjector.get(import29.GestureController));
    this._query_Content_2_0 = new import15.QueryList<any>();
    this._appEl_2.initComponent(this._Menu_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-header',(null as any));
    this._Header_4_3 = new import17.Wrapper_Header(this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import30.ViewController,(null as any)));
    this._text_5 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'ion-toolbar',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','toolbar');
    this._appEl_6 = new import3.AppElement(6,4,this,this._el_6);
    var compView_6:any = import17.viewFactory_Toolbar0(this.viewUtils,this.injector(6),this._appEl_6);
    this._Toolbar_6_4 = new import17.Wrapper_Toolbar(this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_6),this.renderer);
    this._appEl_6.initComponent(this._Toolbar_6_4.context,([] as any[]),compView_6);
    this._text_7 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_8 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_8 = new import3.AppElement(8,6,this,this._el_8);
    var compView_8:any = import18.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(8),this._appEl_8);
    this._ToolbarTitle_8_4 = new import18.Wrapper_ToolbarTitle(this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_8),this.renderer,this._Toolbar_6_4.context,this.parentInjector.get(import31.Navbar,(null as any)));
    this._appEl_8.initComponent(this._ToolbarTitle_8_4.context,([] as any[]),compView_8);
    this._text_9 = this.renderer.createText((null as any),'Menu',(null as any));
    compView_8.create(this._ToolbarTitle_8_4.context,[([] as any[]).concat([this._text_9])],(null as any));
    this._text_10 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_6.create(this._Toolbar_6_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_7,
        this._el_8,
        this._text_10
      ]
      )
    ]
    ,(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n  ',(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','outer-content');
    this._appEl_13 = new import3.AppElement(13,2,this,this._el_13);
    var compView_13:any = import19.viewFactory_Content0(this.viewUtils,this.injector(13),this._appEl_13);
    this._Content_13_4 = new import19.Wrapper_Content(this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_13),this.renderer,this.parentInjector.get(import32.App),this.parentInjector.get(import27.Keyboard),this.parentInjector.get(import28.NgZone),this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import33.Tabs,(null as any)));
    this._appEl_13.initComponent(this._Content_13_4.context,([] as any[]),compView_13);
    this._text_14 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_15 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_15_3 = new import20.Wrapper_List(this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_15),this.renderer,this.parentInjector.get(import29.GestureController));
    this._text_16 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','item');
    this._appEl_17 = new import3.AppElement(17,15,this,this._el_17);
    var compView_17:any = import21.viewFactory_Item0(this.viewUtils,this.injector(17),this._appEl_17);
    this._Item_17_4 = new import21.Wrapper_Item(this.parentInjector.get(import34.Form),this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_17),this.renderer);
    this._ListHeader_17_5 = new import22.Wrapper_ListHeader(this.parentInjector.get(import26.Config),this.renderer,new import25.ElementRef(this._el_17),(null as any));
    this._query_Label_17_0 = new import15.QueryList<any>();
    this._query_Button_17_1 = new import15.QueryList<any>();
    this._query_Icon_17_2 = new import15.QueryList<any>();
    this._appEl_17.initComponent(this._Item_17_4.context,([] as any[]),compView_17);
    this._text_18 = this.renderer.createText((null as any),'\n        Navegação\n      ',(null as any));
    this._query_Label_17_0.reset(([] as any[]));
    this._Item_17_4.context.contentLabel = this._query_Label_17_0.first;
    compView_17.create(this._Item_17_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_18]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_19 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._anchor_20 = this.renderer.createTemplateAnchor(this._el_15,(null as any));
    this._appEl_20 = new import3.AppElement(20,15,this,this._anchor_20);
    this._TemplateRef_20_5 = new import35.TemplateRef_(this._appEl_20,viewFactory_ConferenceApp1);
    this._NgFor_20_6 = new import23.Wrapper_NgFor(this._appEl_20.vcRef,this._TemplateRef_20_5,this.parentInjector.get(import36.IterableDiffers),this.ref);
    this._text_21 = this.renderer.createText(this._el_15,'\n    ',(null as any));
    this._text_22 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    compView_13.create(this._Content_13_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_14,
        this._el_15,
        this._text_22
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_23 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._query_Content_2_0.reset([this._Content_13_4.context]);
    this._Menu_2_4.context.menuContent = this._query_Content_2_0.first;
      compView_2.create(this._Menu_2_4.context,[([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_12,
        this._el_13,
        this._text_23
      ]
    )],(null as any));
    this._text_24 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_25 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_26 = this.renderer.createElement(parentRenderNode,'ion-menu',(null as any));
    this.renderer.setElementAttribute(this._el_26,'id','loggedInMenu');
    this.renderer.setElementAttribute(this._el_26,'role','navigation');
    this._appEl_26 = new import3.AppElement(26,(null as any),this,this._el_26);
    var compView_26:any = import16.viewFactory_Menu0(this.viewUtils,this.injector(26),this._appEl_26);
    this._Menu_26_4 = new import16.Wrapper_Menu(this.parentInjector.get(import10.MenuController),new import25.ElementRef(this._el_26),this.parentInjector.get(import26.Config),this.parentInjector.get(import11.Platform),this.renderer,this.parentInjector.get(import27.Keyboard),this.parentInjector.get(import28.NgZone),this.parentInjector.get(import29.GestureController));
    this._query_Content_26_0 = new import15.QueryList<any>();
    this._appEl_26.initComponent(this._Menu_26_4.context,([] as any[]),compView_26);
    this._text_27 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_28 = this.renderer.createElement((null as any),'ion-header',(null as any));
    this._Header_28_3 = new import17.Wrapper_Header(this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_28),this.renderer,this.parentInjector.get(import30.ViewController,(null as any)));
    this._text_29 = this.renderer.createText(this._el_28,'\n    ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_28,'ion-toolbar',(null as any));
    this.renderer.setElementAttribute(this._el_30,'class','toolbar');
    this._appEl_30 = new import3.AppElement(30,28,this,this._el_30);
    var compView_30:any = import17.viewFactory_Toolbar0(this.viewUtils,this.injector(30),this._appEl_30);
    this._Toolbar_30_4 = new import17.Wrapper_Toolbar(this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_30),this.renderer);
    this._appEl_30.initComponent(this._Toolbar_30_4.context,([] as any[]),compView_30);
    this._text_31 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_32 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_32 = new import3.AppElement(32,30,this,this._el_32);
    var compView_32:any = import18.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(32),this._appEl_32);
    this._ToolbarTitle_32_4 = new import18.Wrapper_ToolbarTitle(this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_32),this.renderer,this._Toolbar_30_4.context,this.parentInjector.get(import31.Navbar,(null as any)));
    this._appEl_32.initComponent(this._ToolbarTitle_32_4.context,([] as any[]),compView_32);
    this._text_33 = this.renderer.createText((null as any),'Menu',(null as any));
    compView_32.create(this._ToolbarTitle_32_4.context,[([] as any[]).concat([this._text_33])],(null as any));
    this._text_34 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_30.create(this._Toolbar_30_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_31,
        this._el_32,
        this._text_34
      ]
      )
    ]
    ,(null as any));
    this._text_35 = this.renderer.createText(this._el_28,'\n  ',(null as any));
    this._text_36 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_37 = this.renderer.createElement((null as any),'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','outer-content');
    this._appEl_37 = new import3.AppElement(37,26,this,this._el_37);
    var compView_37:any = import19.viewFactory_Content0(this.viewUtils,this.injector(37),this._appEl_37);
    this._Content_37_4 = new import19.Wrapper_Content(this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_37),this.renderer,this.parentInjector.get(import32.App),this.parentInjector.get(import27.Keyboard),this.parentInjector.get(import28.NgZone),this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import33.Tabs,(null as any)));
    this._appEl_37.initComponent(this._Content_37_4.context,([] as any[]),compView_37);
    this._text_38 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_39 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_39_3 = new import20.Wrapper_List(this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_39),this.renderer,this.parentInjector.get(import29.GestureController));
    this._text_40 = this.renderer.createText(this._el_39,'\n      ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_39,'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_41,'class','item');
    this._appEl_41 = new import3.AppElement(41,39,this,this._el_41);
    var compView_41:any = import21.viewFactory_Item0(this.viewUtils,this.injector(41),this._appEl_41);
    this._Item_41_4 = new import21.Wrapper_Item(this.parentInjector.get(import34.Form),this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_41),this.renderer);
    this._ListHeader_41_5 = new import22.Wrapper_ListHeader(this.parentInjector.get(import26.Config),this.renderer,new import25.ElementRef(this._el_41),(null as any));
    this._query_Label_41_0 = new import15.QueryList<any>();
    this._query_Button_41_1 = new import15.QueryList<any>();
    this._query_Icon_41_2 = new import15.QueryList<any>();
    this._appEl_41.initComponent(this._Item_41_4.context,([] as any[]),compView_41);
    this._text_42 = this.renderer.createText((null as any),'\n        Navegação\n      ',(null as any));
    this._query_Label_41_0.reset(([] as any[]));
    this._Item_41_4.context.contentLabel = this._query_Label_41_0.first;
    compView_41.create(this._Item_41_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_42]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_43 = this.renderer.createText(this._el_39,'\n      ',(null as any));
    this._anchor_44 = this.renderer.createTemplateAnchor(this._el_39,(null as any));
    this._appEl_44 = new import3.AppElement(44,39,this,this._anchor_44);
    this._TemplateRef_44_5 = new import35.TemplateRef_(this._appEl_44,viewFactory_ConferenceApp2);
    this._NgFor_44_6 = new import23.Wrapper_NgFor(this._appEl_44.vcRef,this._TemplateRef_44_5,this.parentInjector.get(import36.IterableDiffers),this.ref);
    this._text_45 = this.renderer.createText(this._el_39,'\n    ',(null as any));
    this._text_46 = this.renderer.createText((null as any),'\n\n\n  ',(null as any));
    compView_37.create(this._Content_37_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_38,
        this._el_39,
        this._text_46
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_47 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._query_Content_26_0.reset([this._Content_37_4.context]);
    this._Menu_26_4.context.menuContent = this._query_Content_26_0.first;
      compView_26.create(this._Menu_26_4.context,[([] as any[]).concat([
        this._text_27,
        this._el_28,
        this._text_36,
        this._el_37,
        this._text_47
      ]
    )],(null as any));
    this._text_48 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._text_49 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_50 = this.renderer.createElement(parentRenderNode,'ion-nav',(null as any));
    this.renderer.setElementAttribute(this._el_50,'swipeBackEnabled','false');
    this._appEl_50 = new import3.AppElement(50,(null as any),this,this._el_50);
    var compView_50:any = import24.viewFactory_Nav0(this.viewUtils,this.injector(50),this._appEl_50);
    this._Nav_50_4 = new import24.Wrapper_Nav(this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import37.NavControllerBase,(null as any)),this.parentInjector.get(import32.App),this.parentInjector.get(import26.Config),this.parentInjector.get(import27.Keyboard),new import25.ElementRef(this._el_50),this.parentInjector.get(import28.NgZone),this.renderer,this.parentInjector.get(import38.ComponentFactoryResolver),this.parentInjector.get(import29.GestureController),this.parentInjector.get(import39.TransitionController),this.parentInjector.get(import40.DeepLinker,(null as any)));
    this._appEl_50.initComponent(this._Nav_50_4.context,([] as any[]),compView_50);
    compView_50.create(this._Nav_50_4.context,([] as any[]),(null as any));
    this._text_51 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._viewQuery_Nav_0.reset([this._Nav_50_4.context]);
    this.context.nav = this._viewQuery_Nav_0.first;
    this.init(([] as any[]),[
      this._text_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._anchor_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._anchor_44,
      this._text_45,
      this._text_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import41.ToolbarTitle) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._ToolbarTitle_8_4.context; }
    if (((token === import42.Toolbar) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._Toolbar_6_4.context; }
    if (((token === import42.Header) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Header_4_3.context; }
    if (((token === import43.Item) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Item_17_4.context; }
    if (((token === import44.ListHeader) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._ListHeader_17_5.context; }
    if (((token === import35.TemplateRef) && (20 === requestNodeIndex))) { return this._TemplateRef_20_5; }
    if (((token === import45.NgFor) && (20 === requestNodeIndex))) { return this._NgFor_20_6.context; }
    if (((token === import46.List) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._List_15_3.context; }
    if (((token === import47.Content) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._Content_13_4.context; }
    if (((token === import48.Menu) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._Menu_2_4.context; }
    if (((token === import41.ToolbarTitle) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._ToolbarTitle_32_4.context; }
    if (((token === import42.Toolbar) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._Toolbar_30_4.context; }
    if (((token === import42.Header) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._Header_28_3.context; }
    if (((token === import43.Item) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._Item_41_4.context; }
    if (((token === import44.ListHeader) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._ListHeader_41_5.context; }
    if (((token === import35.TemplateRef) && (44 === requestNodeIndex))) { return this._TemplateRef_44_5; }
    if (((token === import45.NgFor) && (44 === requestNodeIndex))) { return this._NgFor_44_6.context; }
    if (((token === import46.List) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._List_39_3.context; }
    if (((token === import47.Content) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._Content_37_4.context; }
    if (((token === import48.Menu) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._Menu_26_4.context; }
    if (((token === import49.Nav) && (50 === requestNodeIndex))) { return this._Nav_50_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this._Nav_50_4.context;
    this._Menu_2_4.check_content(currVal_0,throwOnChange,false);
    const currVal_1:any = 'loggedOutMenu';
    this._Menu_2_4.check_id(currVal_1,throwOnChange,false);
    if (this._Menu_2_4.detectChangesInternal(this,this._el_2,throwOnChange)) { this._appEl_2.componentView.markAsCheckOnce(); }
    this._Header_4_3.detectChangesInternal(this,this._el_4,throwOnChange);
    if (this._Toolbar_6_4.detectChangesInternal(this,this._el_6,throwOnChange)) { this._appEl_6.componentView.markAsCheckOnce(); }
    if (this._ToolbarTitle_8_4.detectChangesInternal(this,this._el_8,throwOnChange)) { this._appEl_8.componentView.markAsCheckOnce(); }
    if (this._Content_13_4.detectChangesInternal(this,this._el_13,throwOnChange)) { this._appEl_13.componentView.markAsCheckOnce(); }
    this._List_15_3.detectChangesInternal(this,this._el_15,throwOnChange);
    if (this._Item_17_4.detectChangesInternal(this,this._el_17,throwOnChange)) { this._appEl_17.componentView.markAsCheckOnce(); }
    this._ListHeader_17_5.detectChangesInternal(this,this._el_17,throwOnChange);
    const currVal_4:any = this.context.appPages;
    this._NgFor_20_6.check_ngForOf(currVal_4,throwOnChange,false);
    this._NgFor_20_6.detectChangesInternal(this,this._anchor_20,throwOnChange);
    const currVal_5:any = this._Nav_50_4.context;
    this._Menu_26_4.check_content(currVal_5,throwOnChange,false);
    const currVal_6:any = 'loggedInMenu';
    this._Menu_26_4.check_id(currVal_6,throwOnChange,false);
    if (this._Menu_26_4.detectChangesInternal(this,this._el_26,throwOnChange)) { this._appEl_26.componentView.markAsCheckOnce(); }
    this._Header_28_3.detectChangesInternal(this,this._el_28,throwOnChange);
    if (this._Toolbar_30_4.detectChangesInternal(this,this._el_30,throwOnChange)) { this._appEl_30.componentView.markAsCheckOnce(); }
    if (this._ToolbarTitle_32_4.detectChangesInternal(this,this._el_32,throwOnChange)) { this._appEl_32.componentView.markAsCheckOnce(); }
    if (this._Content_37_4.detectChangesInternal(this,this._el_37,throwOnChange)) { this._appEl_37.componentView.markAsCheckOnce(); }
    this._List_39_3.detectChangesInternal(this,this._el_39,throwOnChange);
    if (this._Item_41_4.detectChangesInternal(this,this._el_41,throwOnChange)) { this._appEl_41.componentView.markAsCheckOnce(); }
    this._ListHeader_41_5.detectChangesInternal(this,this._el_41,throwOnChange);
    const currVal_9:any = this.context.appPages;
    this._NgFor_44_6.check_ngForOf(currVal_9,throwOnChange,false);
    this._NgFor_44_6.detectChangesInternal(this,this._anchor_44,throwOnChange);
    const currVal_10:any = this.context.rootPage;
    this._Nav_50_4.check_root(currVal_10,throwOnChange,false);
    const currVal_11:any = 'false';
    this._Nav_50_4.check_swipeBackEnabled(currVal_11,throwOnChange,false);
    this._Nav_50_4.detectChangesInternal(this,this._el_50,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_17_1.dirty) {
        this._query_Button_17_1.reset(([] as any[]));
        this._Item_17_4.context._buttons = this._query_Button_17_1;
        this._query_Button_17_1.notifyOnChanges();
      }
      if (this._query_Icon_17_2.dirty) {
        this._query_Icon_17_2.reset(([] as any[]));
        this._Item_17_4.context._icons = this._query_Icon_17_2;
        this._query_Icon_17_2.notifyOnChanges();
      }
      if (this._query_Button_41_1.dirty) {
        this._query_Button_41_1.reset(([] as any[]));
        this._Item_41_4.context._buttons = this._query_Button_41_1;
        this._query_Button_41_1.notifyOnChanges();
      }
      if (this._query_Icon_41_2.dirty) {
        this._query_Icon_41_2.reset(([] as any[]));
        this._Item_41_4.context._icons = this._query_Icon_41_2;
        this._query_Icon_41_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_17_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_41_4.context.ngAfterContentInit(); }
    }
    const currVal_2:any = this._Toolbar_6_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_6,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Content_13_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_13,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_7:any = this._Toolbar_30_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_30,'statusbar-padding',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._Content_37_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_37,'statusbar-padding',currVal_8);
      this._expr_8 = currVal_8;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Nav_50_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_13_4.context.ngOnDestroy();
    this._Menu_2_4.context.ngOnDestroy();
    this._Content_37_4.context.ngOnDestroy();
    this._Menu_26_4.context.ngOnDestroy();
  }
}
export function viewFactory_ConferenceApp0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.ConferenceApp> {
  if ((renderType_ConferenceApp === (null as any))) { (renderType_ConferenceApp = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,styles_ConferenceApp,{})); }
  return new _View_ConferenceApp0(viewUtils,parentInjector,declarationEl);
}
class _View_ConferenceApp1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import21.Wrapper_Item;
  _ItemContent_0_5:import21.Wrapper_ItemContent;
  _MenuClose_0_6:import50.Wrapper_MenuClose;
  _query_Label_0_0:import15.QueryList<any>;
  _query_Button_0_1:import15.QueryList<any>;
  _query_Icon_0_2:import15.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Icon_2_3:import51.Wrapper_Icon;
  _text_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ConferenceApp1,renderType_ConferenceApp,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this.renderer.setElementAttribute(this._el_0,'ion-item','');
    this.renderer.setElementAttribute(this._el_0,'menuClose','');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import21.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import21.Wrapper_Item(this.parent.parentInjector.get(import34.Form),this.parent.parentInjector.get(import26.Config),new import25.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import21.Wrapper_ItemContent();
    this._MenuClose_0_6 = new import50.Wrapper_MenuClose(this.parent.parentInjector.get(import10.MenuController));
    this._query_Label_0_0 = new import15.QueryList<any>();
    this._query_Button_0_1 = new import15.QueryList<any>();
    this._query_Icon_0_2 = new import15.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_2,'item-left','');
    this.renderer.setElementAttribute(this._el_2,'role','img');
    this._Icon_2_3 = new import51.Wrapper_Icon(this.parent.parentInjector.get(import26.Config),new import25.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]).concat([this._el_2]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._text_3
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import52.Icon) && (2 === requestNodeIndex))) { return this._Icon_2_3.context; }
    if (((token === import43.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Item_0_4.context; }
    if (((token === import43.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._ItemContent_0_5.context; }
    if (((token === import53.MenuClose) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._MenuClose_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_2:any = '';
    this._MenuClose_0_6.check_menuClose(currVal_2,throwOnChange,false);
    this._MenuClose_0_6.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_3:any = this.context.$implicit.icon;
    this._Icon_2_3.check_name(currVal_3,throwOnChange,false);
    this._Icon_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset([this._Icon_2_3.context]);
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    const currVal_4:any = this._Icon_2_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_2,'hide',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'\n        ',this.context.$implicit.title,'\n      ');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_3,currVal_5);
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_2_3.context.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.openPage(this.context.$implicit)) !== false);
    const pd_1:any = ((<any>this._MenuClose_0_6.context.close()) !== false);
    return ((true && pd_0) && pd_1);
  }
}
function viewFactory_ConferenceApp1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ConferenceApp1(viewUtils,parentInjector,declarationEl);
}
class _View_ConferenceApp2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import21.Wrapper_Item;
  _ItemContent_0_5:import21.Wrapper_ItemContent;
  _MenuClose_0_6:import50.Wrapper_MenuClose;
  _query_Label_0_0:import15.QueryList<any>;
  _query_Button_0_1:import15.QueryList<any>;
  _query_Icon_0_2:import15.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Icon_2_3:import51.Wrapper_Icon;
  _text_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ConferenceApp2,renderType_ConferenceApp,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this.renderer.setElementAttribute(this._el_0,'ion-item','');
    this.renderer.setElementAttribute(this._el_0,'menuClose','');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import21.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import21.Wrapper_Item(this.parent.parentInjector.get(import34.Form),this.parent.parentInjector.get(import26.Config),new import25.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import21.Wrapper_ItemContent();
    this._MenuClose_0_6 = new import50.Wrapper_MenuClose(this.parent.parentInjector.get(import10.MenuController));
    this._query_Label_0_0 = new import15.QueryList<any>();
    this._query_Button_0_1 = new import15.QueryList<any>();
    this._query_Icon_0_2 = new import15.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_2,'item-left','');
    this.renderer.setElementAttribute(this._el_2,'role','img');
    this._Icon_2_3 = new import51.Wrapper_Icon(this.parent.parentInjector.get(import26.Config),new import25.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]).concat([this._el_2]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._text_3
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import52.Icon) && (2 === requestNodeIndex))) { return this._Icon_2_3.context; }
    if (((token === import43.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Item_0_4.context; }
    if (((token === import43.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._ItemContent_0_5.context; }
    if (((token === import53.MenuClose) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._MenuClose_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_2:any = '';
    this._MenuClose_0_6.check_menuClose(currVal_2,throwOnChange,false);
    this._MenuClose_0_6.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_3:any = this.context.$implicit.icon;
    this._Icon_2_3.check_name(currVal_3,throwOnChange,false);
    this._Icon_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset([this._Icon_2_3.context]);
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    const currVal_4:any = this._Icon_2_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_2,'hide',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'\n        ',this.context.$implicit.title,'\n      ');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_3,currVal_5);
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_2_3.context.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.openPage(this.context.$implicit)) !== false);
    const pd_1:any = ((<any>this._MenuClose_0_6.context.close()) !== false);
    return ((true && pd_0) && pd_1);
  }
}
function viewFactory_ConferenceApp2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ConferenceApp2(viewUtils,parentInjector,declarationEl);
}