/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './schedule-filter';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../providers/conference-data';
import * as import9 from 'ionic-angular/navigation/nav-params';
import * as import10 from 'ionic-angular/navigation/view-controller';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import15 from '@angular/core/src/linker/query_list';
import * as import16 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/list/list-header.ngfactory';
import * as import22 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import23 from '@angular/common/src/pipes/lowercase_pipe';
import * as import24 from 'ionic-angular/config/config';
import * as import25 from '@angular/core/src/linker/element_ref';
import * as import26 from 'ionic-angular/components/navbar/navbar';
import * as import27 from 'ionic-angular/components/app/app';
import * as import28 from 'ionic-angular/util/keyboard';
import * as import29 from '@angular/core/src/zone/ng_zone';
import * as import30 from 'ionic-angular/components/tabs/tabs';
import * as import31 from 'ionic-angular/gestures/gesture-controller';
import * as import32 from 'ionic-angular/util/form';
import * as import33 from '@angular/core/src/linker/template_ref';
import * as import34 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import35 from 'ionic-angular/components/button/button';
import * as import36 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import37 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import38 from 'ionic-angular/components/toolbar/toolbar';
import * as import39 from 'ionic-angular/components/item/item';
import * as import40 from 'ionic-angular/components/list/list-header';
import * as import41 from '@angular/common/src/directives/ng_for';
import * as import42 from 'ionic-angular/components/list/list';
import * as import43 from 'ionic-angular/components/content/content';
import * as import44 from '../../node_modules/ionic-angular/components/label/label.ngfactory';
import * as import45 from '../../node_modules/ionic-angular/components/toggle/toggle.ngfactory';
import * as import46 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import47 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import48 from 'ionic-angular/util/haptic';
import * as import49 from 'ionic-angular/components/label/label';
import * as import50 from 'ionic-angular/components/toggle/toggle';
import * as import51 from '@angular/forms/src/directives/control_value_accessor';
import * as import52 from '@angular/forms/src/directives/ng_model';
import * as import53 from '@angular/forms/src/directives/ng_control';
import * as import54 from '@angular/forms/src/directives/ng_control_status';
export class Wrapper_ScheduleFilterPage {
  context:import0.ScheduleFilterPage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this.context = new import0.ScheduleFilterPage(p0,p1,p2);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_ScheduleFilterPage_Host:import2.RenderComponentType = (null as any);
class _View_ScheduleFilterPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _ScheduleFilterPage_0_4:Wrapper_ScheduleFilterPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ScheduleFilterPage_Host0,renderType_ScheduleFilterPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-schedule-filter',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ScheduleFilterPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ScheduleFilterPage_0_4 = new Wrapper_ScheduleFilterPage(this.parentInjector.get(import8.ConferenceData),this.parentInjector.get(import9.NavParams),this.parentInjector.get(import10.ViewController));
    this._appEl_0.initComponent(this._ScheduleFilterPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._ScheduleFilterPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ScheduleFilterPage) && (0 === requestNodeIndex))) { return this._ScheduleFilterPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ScheduleFilterPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ScheduleFilterPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_ScheduleFilterPage_Host === (null as any))) { (renderType_ScheduleFilterPage_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ScheduleFilterPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const ScheduleFilterPageNgFactory:import12.ComponentFactory<import0.ScheduleFilterPage> = new import12.ComponentFactory<import0.ScheduleFilterPage>('page-schedule-filter',viewFactory_ScheduleFilterPage_Host0,import0.ScheduleFilterPage);
const styles_ScheduleFilterPage:any[] = ([] as any[]);
var renderType_ScheduleFilterPage:import2.RenderComponentType = (null as any);
class _View_ScheduleFilterPage0 extends import1.AppView<import0.ScheduleFilterPage> {
  _el_0:any;
  _Header_0_3:import13.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Toolbar_2_4:import13.Wrapper_Toolbar;
  _text_3:any;
  _el_4:any;
  _ToolbarItem_4_3:import14.Wrapper_ToolbarItem;
  _query_Button_4_0:import15.QueryList<any>;
  _text_5:any;
  _el_6:any;
  /*private*/ _appEl_6:import3.AppElement;
  _Button_6_4:import16.Wrapper_Button;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import3.AppElement;
  _ToolbarTitle_10_4:import17.Wrapper_ToolbarTitle;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _ToolbarItem_13_3:import14.Wrapper_ToolbarItem;
  _query_Button_13_0:import15.QueryList<any>;
  _text_14:any;
  _el_15:any;
  /*private*/ _appEl_15:import3.AppElement;
  _Button_15_4:import16.Wrapper_Button;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  /*private*/ _appEl_21:import3.AppElement;
  _Content_21_4:import18.Wrapper_Content;
  _text_22:any;
  _el_23:any;
  _List_23_3:import19.Wrapper_List;
  _text_24:any;
  _el_25:any;
  /*private*/ _appEl_25:import3.AppElement;
  _Item_25_4:import20.Wrapper_Item;
  _ListHeader_25_5:import21.Wrapper_ListHeader;
  _query_Label_25_0:import15.QueryList<any>;
  _query_Button_25_1:import15.QueryList<any>;
  _query_Icon_25_2:import15.QueryList<any>;
  _text_26:any;
  _text_27:any;
  _anchor_28:any;
  /*private*/ _appEl_28:import3.AppElement;
  _TemplateRef_28_5:any;
  _NgFor_28_6:import22.Wrapper_NgFor;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _List_31_3:import19.Wrapper_List;
  _text_32:any;
  _el_33:any;
  /*private*/ _appEl_33:import3.AppElement;
  _Item_33_4:import20.Wrapper_Item;
  _ItemContent_33_5:import20.Wrapper_ItemContent;
  _query_Label_33_0:import15.QueryList<any>;
  _query_Button_33_1:import15.QueryList<any>;
  _query_Icon_33_2:import15.QueryList<any>;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_3:any;
  _pipe_lowercase_0:import23.LowerCasePipe;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ScheduleFilterPage0,renderType_ScheduleFilterPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import13.Wrapper_Header(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import10.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-toolbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import13.viewFactory_Toolbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Toolbar_2_4 = new import13.Wrapper_Toolbar(this.parentInjector.get(import10.ViewController,(null as any)),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Toolbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_4,'start','');
    this._ToolbarItem_4_3 = new import14.Wrapper_ToolbarItem(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_4),this.renderer,this._Toolbar_2_4.context,this.parentInjector.get(import26.Navbar,(null as any)));
    this._query_Button_4_0 = new import15.QueryList<any>();
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'button',(null as any));
    this.renderer.setElementAttribute(this._el_6,'ion-button','');
    this._appEl_6 = new import3.AppElement(6,4,this,this._el_6);
    var compView_6:any = import16.viewFactory_Button0(this.viewUtils,this.injector(6),this._appEl_6);
    this._Button_6_4 = new import16.Wrapper_Button((null as any),'',this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_6),this.renderer);
    this._appEl_6.initComponent(this._Button_6_4.context,([] as any[]),compView_6);
    this._text_7 = this.renderer.createText((null as any),'Cancel',(null as any));
    compView_6.create(this._Button_6_4.context,[([] as any[]).concat([this._text_7])],(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_10 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_10 = new import3.AppElement(10,2,this,this._el_10);
    var compView_10:any = import17.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(10),this._appEl_10);
    this._ToolbarTitle_10_4 = new import17.Wrapper_ToolbarTitle(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_10),this.renderer,this._Toolbar_2_4.context,this.parentInjector.get(import26.Navbar,(null as any)));
    this._appEl_10.initComponent(this._ToolbarTitle_10_4.context,([] as any[]),compView_10);
    this._text_11 = this.renderer.createText((null as any),'\n      Filter Sessions\n    ',(null as any));
    compView_10.create(this._ToolbarTitle_10_4.context,[([] as any[]).concat([this._text_11])],(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_13,'end','');
    this._ToolbarItem_13_3 = new import14.Wrapper_ToolbarItem(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_13),this.renderer,this._Toolbar_2_4.context,this.parentInjector.get(import26.Navbar,(null as any)));
    this._query_Button_13_0 = new import15.QueryList<any>();
    this._text_14 = this.renderer.createText(this._el_13,'\n      ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'button',(null as any));
    this.renderer.setElementAttribute(this._el_15,'ion-button','');
    this._appEl_15 = new import3.AppElement(15,13,this,this._el_15);
    var compView_15:any = import16.viewFactory_Button0(this.viewUtils,this.injector(15),this._appEl_15);
    this._Button_15_4 = new import16.Wrapper_Button((null as any),'',this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_15),this.renderer);
    this._appEl_15.initComponent(this._Button_15_4.context,([] as any[]),compView_15);
    this._text_16 = this.renderer.createText((null as any),'Done',(null as any));
    compView_15.create(this._Button_15_4.context,[([] as any[]).concat([this._text_16])],(null as any));
    this._text_17 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._text_18 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Toolbar_2_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_4]),
      ([] as any[]).concat([this._el_13]),
      ([] as any[]).concat([
        this._text_3,
        this._text_9,
        this._el_10,
        this._text_12,
        this._text_18
      ]
      )
    ]
    ,(null as any));
    this._text_19 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_20 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_21 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','outer-content');
    this._appEl_21 = new import3.AppElement(21,(null as any),this,this._el_21);
    var compView_21:any = import18.viewFactory_Content0(this.viewUtils,this.injector(21),this._appEl_21);
    this._Content_21_4 = new import18.Wrapper_Content(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_21),this.renderer,this.parentInjector.get(import27.App),this.parentInjector.get(import28.Keyboard),this.parentInjector.get(import29.NgZone),this.parentInjector.get(import10.ViewController,(null as any)),this.parentInjector.get(import30.Tabs,(null as any)));
    this._appEl_21.initComponent(this._Content_21_4.context,([] as any[]),compView_21);
    this._text_22 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_23 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_23_3 = new import19.Wrapper_List(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_23),this.renderer,this.parentInjector.get(import31.GestureController));
    this._text_24 = this.renderer.createText(this._el_23,'\n    ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_23,'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','item');
    this._appEl_25 = new import3.AppElement(25,23,this,this._el_25);
    var compView_25:any = import20.viewFactory_Item0(this.viewUtils,this.injector(25),this._appEl_25);
    this._Item_25_4 = new import20.Wrapper_Item(this.parentInjector.get(import32.Form),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_25),this.renderer);
    this._ListHeader_25_5 = new import21.Wrapper_ListHeader(this.parentInjector.get(import24.Config),this.renderer,new import25.ElementRef(this._el_25),(null as any));
    this._query_Label_25_0 = new import15.QueryList<any>();
    this._query_Button_25_1 = new import15.QueryList<any>();
    this._query_Icon_25_2 = new import15.QueryList<any>();
    this._appEl_25.initComponent(this._Item_25_4.context,([] as any[]),compView_25);
    this._text_26 = this.renderer.createText((null as any),'Tracks',(null as any));
    this._query_Label_25_0.reset(([] as any[]));
    this._Item_25_4.context.contentLabel = this._query_Label_25_0.first;
    compView_25.create(this._Item_25_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_26]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_27 = this.renderer.createText(this._el_23,'\n\n    ',(null as any));
    this._anchor_28 = this.renderer.createTemplateAnchor(this._el_23,(null as any));
    this._appEl_28 = new import3.AppElement(28,23,this,this._anchor_28);
    this._TemplateRef_28_5 = new import33.TemplateRef_(this._appEl_28,viewFactory_ScheduleFilterPage1);
    this._NgFor_28_6 = new import22.Wrapper_NgFor(this._appEl_28.vcRef,this._TemplateRef_28_5,this.parentInjector.get(import34.IterableDiffers),this.ref);
    this._text_29 = this.renderer.createText(this._el_23,'\n\n  ',(null as any));
    this._text_30 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_31 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_31_3 = new import19.Wrapper_List(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_31),this.renderer,this.parentInjector.get(import31.GestureController));
    this._text_32 = this.renderer.createText(this._el_31,'\n    ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_31,'button',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','reset-filters item item-block');
    this.renderer.setElementAttribute(this._el_33,'detail-none','');
    this.renderer.setElementAttribute(this._el_33,'ion-item','');
    this._appEl_33 = new import3.AppElement(33,31,this,this._el_33);
    var compView_33:any = import20.viewFactory_Item0(this.viewUtils,this.injector(33),this._appEl_33);
    this._Item_33_4 = new import20.Wrapper_Item(this.parentInjector.get(import32.Form),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_33),this.renderer);
    this._ItemContent_33_5 = new import20.Wrapper_ItemContent();
    this._query_Label_33_0 = new import15.QueryList<any>();
    this._query_Button_33_1 = new import15.QueryList<any>();
    this._query_Icon_33_2 = new import15.QueryList<any>();
    this._appEl_33.initComponent(this._Item_33_4.context,([] as any[]),compView_33);
    this._text_34 = this.renderer.createText((null as any),'\n      Reset All Filters\n    ',(null as any));
    this._query_Label_33_0.reset(([] as any[]));
    this._Item_33_4.context.contentLabel = this._query_Label_33_0.first;
    compView_33.create(this._Item_33_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_34]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_35 = this.renderer.createText(this._el_31,'\n  ',(null as any));
    this._text_36 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_21.create(this._Content_21_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_22,
        this._el_23,
        this._text_30,
        this._el_31,
        this._text_36
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_37 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_6,'click',this.eventHandler(this._handle_click_6_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_15,'click',this.eventHandler(this._handle_click_15_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._pipe_lowercase_0 = new import23.LowerCasePipe();
    var disposable_2:Function = this.renderer.listen(this._el_33,'click',this.eventHandler(this._handle_click_33_0.bind(this)));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._anchor_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._text_37
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import35.Button) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_6_4.context; }
    if (((token === import36.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._ToolbarItem_4_3.context; }
    if (((token === import37.ToolbarTitle) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._ToolbarTitle_10_4.context; }
    if (((token === import35.Button) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._Button_15_4.context; }
    if (((token === import36.ToolbarItem) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._ToolbarItem_13_3.context; }
    if (((token === import38.Toolbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Toolbar_2_4.context; }
    if (((token === import38.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._Header_0_3.context; }
    if (((token === import39.Item) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Item_25_4.context; }
    if (((token === import40.ListHeader) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._ListHeader_25_5.context; }
    if (((token === import33.TemplateRef) && (28 === requestNodeIndex))) { return this._TemplateRef_28_5; }
    if (((token === import41.NgFor) && (28 === requestNodeIndex))) { return this._NgFor_28_6.context; }
    if (((token === import42.List) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._List_23_3.context; }
    if (((token === import39.Item) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._Item_33_4.context; }
    if (((token === import39.ItemContent) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._ItemContent_33_5.context; }
    if (((token === import42.List) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._List_31_3.context; }
    if (((token === import43.Content) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._Content_21_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    if (this._Toolbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange)) { this._appEl_2.componentView.markAsCheckOnce(); }
    this._ToolbarItem_4_3.detectChangesInternal(this,this._el_4,throwOnChange);
    if (this._Button_6_4.detectChangesInternal(this,this._el_6,throwOnChange)) { this._appEl_6.componentView.markAsCheckOnce(); }
    if (this._ToolbarTitle_10_4.detectChangesInternal(this,this._el_10,throwOnChange)) { this._appEl_10.componentView.markAsCheckOnce(); }
    this._ToolbarItem_13_3.detectChangesInternal(this,this._el_13,throwOnChange);
    if (this._Button_15_4.detectChangesInternal(this,this._el_15,throwOnChange)) { this._appEl_15.componentView.markAsCheckOnce(); }
    if (this._Content_21_4.detectChangesInternal(this,this._el_21,throwOnChange)) { this._appEl_21.componentView.markAsCheckOnce(); }
    this._List_23_3.detectChangesInternal(this,this._el_23,throwOnChange);
    if (this._Item_25_4.detectChangesInternal(this,this._el_25,throwOnChange)) { this._appEl_25.componentView.markAsCheckOnce(); }
    this._ListHeader_25_5.detectChangesInternal(this,this._el_25,throwOnChange);
    const currVal_4:any = this.context.tracks;
    this._NgFor_28_6.check_ngForOf(currVal_4,throwOnChange,false);
    this._NgFor_28_6.detectChangesInternal(this,this._anchor_28,throwOnChange);
    this._List_31_3.detectChangesInternal(this,this._el_31,throwOnChange);
    if (this._Item_33_4.detectChangesInternal(this,this._el_33,throwOnChange)) { this._appEl_33.componentView.markAsCheckOnce(); }
    this._ItemContent_33_5.detectChangesInternal(this,this._el_33,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_6_4.context]);
        this._ToolbarItem_4_3.context._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if (this._query_Button_13_0.dirty) {
        this._query_Button_13_0.reset([this._Button_15_4.context]);
        this._ToolbarItem_13_3.context._buttons = this._query_Button_13_0;
        this._query_Button_13_0.notifyOnChanges();
      }
      if (this._query_Button_25_1.dirty) {
        this._query_Button_25_1.reset(([] as any[]));
        this._Item_25_4.context._buttons = this._query_Button_25_1;
        this._query_Button_25_1.notifyOnChanges();
      }
      if (this._query_Icon_25_2.dirty) {
        this._query_Icon_25_2.reset(([] as any[]));
        this._Item_25_4.context._icons = this._query_Icon_25_2;
        this._query_Icon_25_2.notifyOnChanges();
      }
      if (this._query_Button_33_1.dirty) {
        this._query_Button_33_1.reset(([] as any[]));
        this._Item_33_4.context._buttons = this._query_Button_33_1;
        this._query_Button_33_1.notifyOnChanges();
      }
      if (this._query_Icon_33_2.dirty) {
        this._query_Icon_33_2.reset(([] as any[]));
        this._Item_33_4.context._icons = this._query_Icon_33_2;
        this._query_Icon_33_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_6_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_15_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_25_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_33_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Toolbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_3:any = this._Content_21_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_21,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Content_21_4.context.ngOnDestroy();
  }
  private _handle_click_6_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.dismiss()) !== false);
    return (true && pd_0);
  }
  private _handle_click_15_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.applyFilters()) !== false);
    return (true && pd_0);
  }
  private _handle_click_33_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.resetFilters()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ScheduleFilterPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.ScheduleFilterPage> {
  if ((renderType_ScheduleFilterPage === (null as any))) { (renderType_ScheduleFilterPage = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,styles_ScheduleFilterPage,{})); }
  return new _View_ScheduleFilterPage0(viewUtils,parentInjector,declarationEl);
}
class _View_ScheduleFilterPage1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import20.Wrapper_Item;
  _ItemContent_0_5:import20.Wrapper_ItemContent;
  _query_Label_0_0:import15.QueryList<any>;
  _query_Button_0_1:import15.QueryList<any>;
  _query_Icon_0_2:import15.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _Label_4_3:import44.Wrapper_Label;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  /*private*/ _appEl_7:import3.AppElement;
  _Toggle_7_4:import45.Wrapper_Toggle;
  _NG_VALUE_ACCESSOR_7_5:any[];
  _NgModel_7_6:import46.Wrapper_NgModel;
  _NgControl_7_7:any;
  _NgControlStatus_7_8:import47.Wrapper_NgControlStatus;
  _text_8:any;
  _pipe_lowercase_0_0:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ScheduleFilterPage1,renderType_ScheduleFilterPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import20.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import20.Wrapper_Item(this.parent.parentInjector.get(import32.Form),this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import20.Wrapper_ItemContent();
    this._query_Label_0_0 = new import15.QueryList<any>();
    this._query_Button_0_1 = new import15.QueryList<any>();
    this._query_Icon_0_2 = new import15.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'span',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','dot');
    this.renderer.setElementAttribute(this._el_2,'item-left','');
    this._text_3 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_4_3 = new import44.Wrapper_Label(this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_4),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'ion-toggle',(null as any));
    this.renderer.setElementAttribute(this._el_7,'color','secondary');
    this._appEl_7 = new import3.AppElement(7,0,this,this._el_7);
    var compView_7:any = import45.viewFactory_Toggle0(this.viewUtils,this.injector(7),this._appEl_7);
    this._Toggle_7_4 = new import45.Wrapper_Toggle(this.parent.parentInjector.get(import32.Form),this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_7),this.renderer,this.parent.parentInjector.get(import48.Haptic),this._Item_0_4.context);
    this._NG_VALUE_ACCESSOR_7_5 = [this._Toggle_7_4.context];
    this._NgModel_7_6 = new import46.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_7_5);
    this._NgControl_7_7 = this._NgModel_7_6.context;
    this._NgControlStatus_7_8 = new import47.Wrapper_NgControlStatus(this._NgControl_7_7);
    this._appEl_7.initComponent(this._Toggle_7_4.context,([] as any[]),compView_7);
    compView_7.create(this._Toggle_7_4.context,([] as any[]),(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_0_0.reset([this._Label_4_3.context]);
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]).concat([this._el_2]),
      ([] as any[]).concat([this._el_4]),
      ([] as any[]).concat([
        this._text_1,
        this._text_3,
        this._text_6,
        this._text_8
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([this._el_7])
    ]
    ,(null as any));
    this._pipe_lowercase_0_0 = import4.pureProxy1((<_View_ScheduleFilterPage0>this.parent)._pipe_lowercase_0.transform.bind((<_View_ScheduleFilterPage0>this.parent)._pipe_lowercase_0));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_7,'ngModelChange',this.eventHandler(this._handle_ngModelChange_7_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_7_6.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_7_0.bind(this)));
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8
    ]
    ,[disposable_0],[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import49.Label) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._Label_4_3.context; }
    if (((token === import50.Toggle) && (7 === requestNodeIndex))) { return this._Toggle_7_4.context; }
    if (((token === import51.NG_VALUE_ACCESSOR) && (7 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_7_5; }
    if (((token === import52.NgModel) && (7 === requestNodeIndex))) { return this._NgModel_7_6.context; }
    if (((token === import53.NgControl) && (7 === requestNodeIndex))) { return this._NgControl_7_7; }
    if (((token === import54.NgControlStatus) && (7 === requestNodeIndex))) { return this._NgControlStatus_7_8.context; }
    if (((token === import39.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Item_0_4.context; }
    if (((token === import39.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._ItemContent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Label_4_3.detectChangesInternal(this,this._el_4,throwOnChange);
    const currVal_3:any = 'secondary';
    this._Toggle_7_4.check_color(currVal_3,throwOnChange,false);
    this._Toggle_7_4.detectChangesInternal(this,this._el_7,throwOnChange);
    const currVal_5:any = this.context.$implicit.isChecked;
    this._NgModel_7_6.check_model(currVal_5,throwOnChange,false);
    this._NgModel_7_6.detectChangesInternal(this,this._el_7,throwOnChange);
    this._NgControlStatus_7_8.detectChangesInternal(this,this._el_7,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Toggle_7_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    valUnwrapper.reset();
    const currVal_0:any = valUnwrapper.unwrap(import4.castByValue(this._pipe_lowercase_0_0,(<_View_ScheduleFilterPage0>this.parent)._pipe_lowercase_0.transform)(this.context.$implicit.name));
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_0,currVal_0))) {
      this.renderer.setElementAttribute(this._el_0,'track',((currVal_0 == (null as any))? (null as any): currVal_0.toString()));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'',this.context.$implicit.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_5,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._Toggle_7_4.context._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_7,'toggle-disabled',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._NgControlStatus_7_8.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_7,'ng-untouched',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatus_7_8.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_7,'ng-touched',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatus_7_8.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_7,'ng-pristine',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_7_8.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_7,'ng-dirty',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatus_7_8.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_7,'ng-valid',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatus_7_8.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_7,'ng-invalid',currVal_11);
      this._expr_11 = currVal_11;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Toggle_7_4.context.ngOnDestroy();
    this._NgModel_7_6.context.ngOnDestroy();
  }
  private _handle_ngModelChange_7_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.$implicit.isChecked = $event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ScheduleFilterPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ScheduleFilterPage1(viewUtils,parentInjector,declarationEl);
}