/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './about-popover';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/view-controller';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import12 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import13 from '@angular/core/src/linker/query_list';
import * as import14 from 'ionic-angular/config/config';
import * as import15 from '@angular/core/src/linker/element_ref';
import * as import16 from 'ionic-angular/gestures/gesture-controller';
import * as import17 from 'ionic-angular/util/form';
import * as import18 from 'ionic-angular/components/item/item';
import * as import19 from 'ionic-angular/components/list/list';
export class Wrapper_PopoverPage {
  context:import0.PopoverPage;
  changed:boolean;
  constructor(p0:any) {
    this.changed = false;
    this.context = new import0.PopoverPage(p0);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_PopoverPage_Host:import2.RenderComponentType = (null as any);
class _View_PopoverPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _PopoverPage_0_4:Wrapper_PopoverPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PopoverPage_Host0,renderType_PopoverPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_PopoverPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._PopoverPage_0_4 = new Wrapper_PopoverPage(this.parentInjector.get(import8.ViewController));
    this._appEl_0.initComponent(this._PopoverPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._PopoverPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.PopoverPage) && (0 === requestNodeIndex))) { return this._PopoverPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._PopoverPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_PopoverPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_PopoverPage_Host === (null as any))) { (renderType_PopoverPage_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_PopoverPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const PopoverPageNgFactory:import10.ComponentFactory<import0.PopoverPage> = new import10.ComponentFactory<import0.PopoverPage>('ng-component',viewFactory_PopoverPage_Host0,import0.PopoverPage);
const styles_PopoverPage:any[] = ([] as any[]);
var renderType_PopoverPage:import2.RenderComponentType = (null as any);
class _View_PopoverPage0 extends import1.AppView<import0.PopoverPage> {
  _el_0:any;
  _List_0_3:import11.Wrapper_List;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Item_2_4:import12.Wrapper_Item;
  _ItemContent_2_5:import12.Wrapper_ItemContent;
  _query_Label_2_0:import13.QueryList<any>;
  _query_Button_2_1:import13.QueryList<any>;
  _query_Icon_2_2:import13.QueryList<any>;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _Item_5_4:import12.Wrapper_Item;
  _ItemContent_5_5:import12.Wrapper_ItemContent;
  _query_Label_5_0:import13.QueryList<any>;
  _query_Button_5_1:import13.QueryList<any>;
  _query_Icon_5_2:import13.QueryList<any>;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  /*private*/ _appEl_8:import3.AppElement;
  _Item_8_4:import12.Wrapper_Item;
  _ItemContent_8_5:import12.Wrapper_ItemContent;
  _query_Label_8_0:import13.QueryList<any>;
  _query_Button_8_1:import13.QueryList<any>;
  _query_Icon_8_2:import13.QueryList<any>;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  /*private*/ _appEl_11:import3.AppElement;
  _Item_11_4:import12.Wrapper_Item;
  _ItemContent_11_5:import12.Wrapper_ItemContent;
  _query_Label_11_0:import13.QueryList<any>;
  _query_Button_11_1:import13.QueryList<any>;
  _query_Icon_11_2:import13.QueryList<any>;
  _text_12:any;
  _text_13:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PopoverPage0,renderType_PopoverPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-list',(null as any));
    this._List_0_3 = new import11.Wrapper_List(this.parentInjector.get(import14.Config),new import15.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import16.GestureController));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','item item-block');
    this.renderer.setElementAttribute(this._el_2,'ion-item','');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import12.viewFactory_Item0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Item_2_4 = new import12.Wrapper_Item(this.parentInjector.get(import17.Form),this.parentInjector.get(import14.Config),new import15.ElementRef(this._el_2),this.renderer);
    this._ItemContent_2_5 = new import12.Wrapper_ItemContent();
    this._query_Label_2_0 = new import13.QueryList<any>();
    this._query_Button_2_1 = new import13.QueryList<any>();
    this._query_Icon_2_2 = new import13.QueryList<any>();
    this._appEl_2.initComponent(this._Item_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'Learn Ionic',(null as any));
    this._query_Label_2_0.reset(([] as any[]));
    this._Item_2_4.context.contentLabel = this._query_Label_2_0.first;
    compView_2.create(this._Item_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_3]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','item item-block');
    this.renderer.setElementAttribute(this._el_5,'ion-item','');
    this._appEl_5 = new import3.AppElement(5,0,this,this._el_5);
    var compView_5:any = import12.viewFactory_Item0(this.viewUtils,this.injector(5),this._appEl_5);
    this._Item_5_4 = new import12.Wrapper_Item(this.parentInjector.get(import17.Form),this.parentInjector.get(import14.Config),new import15.ElementRef(this._el_5),this.renderer);
    this._ItemContent_5_5 = new import12.Wrapper_ItemContent();
    this._query_Label_5_0 = new import13.QueryList<any>();
    this._query_Button_5_1 = new import13.QueryList<any>();
    this._query_Icon_5_2 = new import13.QueryList<any>();
    this._appEl_5.initComponent(this._Item_5_4.context,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'Documentation',(null as any));
    this._query_Label_5_0.reset(([] as any[]));
    this._Item_5_4.context.contentLabel = this._query_Label_5_0.first;
    compView_5.create(this._Item_5_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_6]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','item item-block');
    this.renderer.setElementAttribute(this._el_8,'ion-item','');
    this._appEl_8 = new import3.AppElement(8,0,this,this._el_8);
    var compView_8:any = import12.viewFactory_Item0(this.viewUtils,this.injector(8),this._appEl_8);
    this._Item_8_4 = new import12.Wrapper_Item(this.parentInjector.get(import17.Form),this.parentInjector.get(import14.Config),new import15.ElementRef(this._el_8),this.renderer);
    this._ItemContent_8_5 = new import12.Wrapper_ItemContent();
    this._query_Label_8_0 = new import13.QueryList<any>();
    this._query_Button_8_1 = new import13.QueryList<any>();
    this._query_Icon_8_2 = new import13.QueryList<any>();
    this._appEl_8.initComponent(this._Item_8_4.context,([] as any[]),compView_8);
    this._text_9 = this.renderer.createText((null as any),'Showcase',(null as any));
    this._query_Label_8_0.reset(([] as any[]));
    this._Item_8_4.context.contentLabel = this._query_Label_8_0.first;
    compView_8.create(this._Item_8_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_9]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','item item-block');
    this.renderer.setElementAttribute(this._el_11,'ion-item','');
    this._appEl_11 = new import3.AppElement(11,0,this,this._el_11);
    var compView_11:any = import12.viewFactory_Item0(this.viewUtils,this.injector(11),this._appEl_11);
    this._Item_11_4 = new import12.Wrapper_Item(this.parentInjector.get(import17.Form),this.parentInjector.get(import14.Config),new import15.ElementRef(this._el_11),this.renderer);
    this._ItemContent_11_5 = new import12.Wrapper_ItemContent();
    this._query_Label_11_0 = new import13.QueryList<any>();
    this._query_Button_11_1 = new import13.QueryList<any>();
    this._query_Icon_11_2 = new import13.QueryList<any>();
    this._appEl_11.initComponent(this._Item_11_4.context,([] as any[]),compView_11);
    this._text_12 = this.renderer.createText((null as any),'GitHub Repo',(null as any));
    this._query_Label_11_0.reset(([] as any[]));
    this._Item_11_4.context.contentLabel = this._query_Label_11_0.first;
    compView_11.create(this._Item_11_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_12]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_13 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_5,'click',this.eventHandler(this._handle_click_5_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_8,'click',this.eventHandler(this._handle_click_8_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_11,'click',this.eventHandler(this._handle_click_11_0.bind(this)));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.Item) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Item_2_4.context; }
    if (((token === import18.ItemContent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._ItemContent_2_5.context; }
    if (((token === import18.Item) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Item_5_4.context; }
    if (((token === import18.ItemContent) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ItemContent_5_5.context; }
    if (((token === import18.Item) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Item_8_4.context; }
    if (((token === import18.ItemContent) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._ItemContent_8_5.context; }
    if (((token === import18.Item) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Item_11_4.context; }
    if (((token === import18.ItemContent) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._ItemContent_11_5.context; }
    if (((token === import19.List) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._List_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._List_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    if (this._Item_2_4.detectChangesInternal(this,this._el_2,throwOnChange)) { this._appEl_2.componentView.markAsCheckOnce(); }
    this._ItemContent_2_5.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._Item_5_4.detectChangesInternal(this,this._el_5,throwOnChange)) { this._appEl_5.componentView.markAsCheckOnce(); }
    this._ItemContent_5_5.detectChangesInternal(this,this._el_5,throwOnChange);
    if (this._Item_8_4.detectChangesInternal(this,this._el_8,throwOnChange)) { this._appEl_8.componentView.markAsCheckOnce(); }
    this._ItemContent_8_5.detectChangesInternal(this,this._el_8,throwOnChange);
    if (this._Item_11_4.detectChangesInternal(this,this._el_11,throwOnChange)) { this._appEl_11.componentView.markAsCheckOnce(); }
    this._ItemContent_11_5.detectChangesInternal(this,this._el_11,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_2_1.dirty) {
        this._query_Button_2_1.reset(([] as any[]));
        this._Item_2_4.context._buttons = this._query_Button_2_1;
        this._query_Button_2_1.notifyOnChanges();
      }
      if (this._query_Icon_2_2.dirty) {
        this._query_Icon_2_2.reset(([] as any[]));
        this._Item_2_4.context._icons = this._query_Icon_2_2;
        this._query_Icon_2_2.notifyOnChanges();
      }
      if (this._query_Button_5_1.dirty) {
        this._query_Button_5_1.reset(([] as any[]));
        this._Item_5_4.context._buttons = this._query_Button_5_1;
        this._query_Button_5_1.notifyOnChanges();
      }
      if (this._query_Icon_5_2.dirty) {
        this._query_Icon_5_2.reset(([] as any[]));
        this._Item_5_4.context._icons = this._query_Icon_5_2;
        this._query_Icon_5_2.notifyOnChanges();
      }
      if (this._query_Button_8_1.dirty) {
        this._query_Button_8_1.reset(([] as any[]));
        this._Item_8_4.context._buttons = this._query_Button_8_1;
        this._query_Button_8_1.notifyOnChanges();
      }
      if (this._query_Icon_8_2.dirty) {
        this._query_Icon_8_2.reset(([] as any[]));
        this._Item_8_4.context._icons = this._query_Icon_8_2;
        this._query_Icon_8_2.notifyOnChanges();
      }
      if (this._query_Button_11_1.dirty) {
        this._query_Button_11_1.reset(([] as any[]));
        this._Item_11_4.context._buttons = this._query_Button_11_1;
        this._query_Button_11_1.notifyOnChanges();
      }
      if (this._query_Icon_11_2.dirty) {
        this._query_Icon_11_2.reset(([] as any[]));
        this._Item_11_4.context._icons = this._query_Icon_11_2;
        this._query_Icon_11_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_2_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_5_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_8_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_11_4.context.ngAfterContentInit(); }
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.close()) !== false);
    return (true && pd_0);
  }
  private _handle_click_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.close()) !== false);
    return (true && pd_0);
  }
  private _handle_click_8_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.close()) !== false);
    return (true && pd_0);
  }
  private _handle_click_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.close()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_PopoverPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.PopoverPage> {
  if ((renderType_PopoverPage === (null as any))) { (renderType_PopoverPage = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_PopoverPage,{})); }
  return new _View_PopoverPage0(viewUtils,parentInjector,declarationEl);
}