/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './account';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/components/alert/alert';
import * as import9 from 'ionic-angular/navigation/nav-controller';
import * as import10 from '../../providers/user-data';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/menu/menu-toggle.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import18 from '@angular/core/src/linker/query_list';
import * as import19 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import22 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import23 from 'ionic-angular/config/config';
import * as import24 from '@angular/core/src/linker/element_ref';
import * as import25 from 'ionic-angular/navigation/view-controller';
import * as import26 from 'ionic-angular/components/app/app';
import * as import27 from 'ionic-angular/components/menu/menu-controller';
import * as import28 from 'ionic-angular/components/toolbar/toolbar';
import * as import29 from 'ionic-angular/util/keyboard';
import * as import30 from '@angular/core/src/zone/ng_zone';
import * as import31 from 'ionic-angular/components/tabs/tabs';
import * as import32 from '@angular/core/src/linker/template_ref';
import * as import33 from 'ionic-angular/components/icon/icon';
import * as import34 from 'ionic-angular/components/button/button';
import * as import35 from 'ionic-angular/components/menu/menu-toggle';
import * as import36 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import37 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import38 from 'ionic-angular/components/navbar/navbar';
import * as import39 from '@angular/common/src/directives/ng_if';
import * as import40 from 'ionic-angular/components/content/content';
import * as import41 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import42 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import43 from 'ionic-angular/gestures/gesture-controller';
import * as import44 from 'ionic-angular/util/form';
import * as import45 from 'ionic-angular/components/item/item';
import * as import46 from 'ionic-angular/components/list/list';
export class Wrapper_AccountPage {
  context:import0.AccountPage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this.context = new import0.AccountPage(p0,p1,p2);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_AccountPage_Host:import2.RenderComponentType = (null as any);
class _View_AccountPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _AccountPage_0_4:Wrapper_AccountPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AccountPage_Host0,renderType_AccountPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-account',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AccountPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AccountPage_0_4 = new Wrapper_AccountPage(this.parentInjector.get(import8.AlertController),this.parentInjector.get(import9.NavController),this.parentInjector.get(import10.UserData));
    this._appEl_0.initComponent(this._AccountPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._AccountPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AccountPage) && (0 === requestNodeIndex))) { return this._AccountPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AccountPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._AccountPage_0_4.context.ngAfterViewInit(); } }
  }
}
function viewFactory_AccountPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_AccountPage_Host === (null as any))) { (renderType_AccountPage_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_AccountPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const AccountPageNgFactory:import12.ComponentFactory<import0.AccountPage> = new import12.ComponentFactory<import0.AccountPage>('page-account',viewFactory_AccountPage_Host0,import0.AccountPage);
const styles_AccountPage:any[] = ([] as any[]);
var renderType_AccountPage:import2.RenderComponentType = (null as any);
class _View_AccountPage0 extends import1.AppView<import0.AccountPage> {
  _el_0:any;
  _Header_0_3:import13.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import14.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _Button_4_4:import15.Wrapper_Button;
  _MenuToggle_4_5:import16.Wrapper_MenuToggle;
  _ToolbarItem_4_6:import17.Wrapper_ToolbarItem;
  _query_Button_4_0:import18.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import19.Wrapper_Icon;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _ToolbarTitle_9_4:import20.Wrapper_ToolbarTitle;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import3.AppElement;
  _Content_14_4:import21.Wrapper_Content;
  _text_15:any;
  _anchor_16:any;
  /*private*/ _appEl_16:import3.AppElement;
  _TemplateRef_16_5:any;
  _NgIf_16_6:import22.Wrapper_NgIf;
  _text_17:any;
  _text_18:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AccountPage0,renderType_AccountPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import13.Wrapper_Header(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import25.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import14.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import14.Wrapper_Navbar(this.parentInjector.get(import26.App),this.parentInjector.get(import25.ViewController,(null as any)),this.parentInjector.get(import9.NavController,(null as any)),this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'ion-button','');
    this.renderer.setElementAttribute(this._el_4,'menuToggle','');
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import15.viewFactory_Button0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Button_4_4 = new import15.Wrapper_Button('','',this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_4),this.renderer);
    this._MenuToggle_4_5 = new import16.Wrapper_MenuToggle(this.parentInjector.get(import27.MenuController),new import24.ElementRef(this._el_4),this.parentInjector.get(import25.ViewController,(null as any)),this._Navbar_2_4.context);
    this._ToolbarItem_4_6 = new import17.Wrapper_ToolbarItem(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import28.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._query_Button_4_0 = new import18.QueryList<any>();
    this._appEl_4.initComponent(this._Button_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'name','menu');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._Icon_6_3 = new import19.Wrapper_Icon(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_4.create(this._Button_4_4.context,[([] as any[]).concat([
        this._text_5,
        this._el_6,
        this._text_7
      ]
    )],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_9 = new import3.AppElement(9,2,this,this._el_9);
    var compView_9:any = import20.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(9),this._appEl_9);
    this._ToolbarTitle_9_4 = new import20.Wrapper_ToolbarTitle(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import28.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_9.initComponent(this._ToolbarTitle_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'Account',(null as any));
    compView_9.create(this._ToolbarTitle_9_4.context,[([] as any[]).concat([this._text_10])],(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]).concat([this._el_4]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_11
      ]
      )
    ]
    ,(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_14 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','outer-content');
    this._appEl_14 = new import3.AppElement(14,(null as any),this,this._el_14);
    var compView_14:any = import21.viewFactory_Content0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Content_14_4 = new import21.Wrapper_Content(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import26.App),this.parentInjector.get(import29.Keyboard),this.parentInjector.get(import30.NgZone),this.parentInjector.get(import25.ViewController,(null as any)),this.parentInjector.get(import31.Tabs,(null as any)));
    this._appEl_14.initComponent(this._Content_14_4.context,([] as any[]),compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._anchor_16 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_16 = new import3.AppElement(16,14,this,this._anchor_16);
    this._TemplateRef_16_5 = new import32.TemplateRef_(this._appEl_16,viewFactory_AccountPage1);
    this._NgIf_16_6 = new import22.Wrapper_NgIf(this._appEl_16.vcRef,this._TemplateRef_16_5);
    this._text_17 = this.renderer.createText((null as any),'\n',(null as any));
    compView_14.create(this._Content_14_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_15,
        this._appEl_16,
        this._text_17
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_18 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._anchor_16,
      this._text_17,
      this._text_18
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import33.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3.context; }
    if (((token === import34.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_4_4.context; }
    if (((token === import35.MenuToggle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._MenuToggle_4_5.context; }
    if (((token === import36.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarItem_4_6.context; }
    if (((token === import37.ToolbarTitle) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarTitle_9_4.context; }
    if (((token === import38.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Navbar_2_4.context; }
    if (((token === import28.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Header_0_3.context; }
    if (((token === import32.TemplateRef) && (16 === requestNodeIndex))) { return this._TemplateRef_16_5; }
    if (((token === import39.NgIf) && (16 === requestNodeIndex))) { return this._NgIf_16_6.context; }
    if (((token === import40.Content) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Content_14_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._Button_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    const currVal_3:any = '';
    this._MenuToggle_4_5.check_menuToggle(currVal_3,throwOnChange,false);
    this._MenuToggle_4_5.detectChangesInternal(this,this._el_4,throwOnChange);
    this._ToolbarItem_4_6.detectChangesInternal(this,this._el_4,throwOnChange);
    const currVal_5:any = 'menu';
    this._Icon_6_3.check_name(currVal_5,throwOnChange,false);
    this._Icon_6_3.detectChangesInternal(this,this._el_6,throwOnChange);
    if (this._ToolbarTitle_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    if (this._Content_14_4.detectChangesInternal(this,this._el_14,throwOnChange)) { this._appEl_14.componentView.markAsCheckOnce(); }
    const currVal_8:any = this.context.username;
    this._NgIf_16_6.check_ngIf(currVal_8,throwOnChange,false);
    this._NgIf_16_6.detectChangesInternal(this,this._anchor_16,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_4_4.context]);
        this._ToolbarItem_4_6.context._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_4_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_4_5.context.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_4,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_6_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._Content_14_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_14,'statusbar-padding',currVal_7);
      this._expr_7 = currVal_7;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_6_3.context.ngOnDestroy();
    this._Content_14_4.context.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_4_5.context.toggle()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_AccountPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.AccountPage> {
  if ((renderType_AccountPage === (null as any))) { (renderType_AccountPage = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,styles_AccountPage,{})); }
  return new _View_AccountPage0(viewUtils,parentInjector,declarationEl);
}
class _View_AccountPage1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _List_7_3:import41.Wrapper_List;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _Item_9_4:import42.Wrapper_Item;
  _ItemContent_9_5:import42.Wrapper_ItemContent;
  _query_Label_9_0:import18.QueryList<any>;
  _query_Button_9_1:import18.QueryList<any>;
  _query_Icon_9_2:import18.QueryList<any>;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import3.AppElement;
  _Item_12_4:import42.Wrapper_Item;
  _ItemContent_12_5:import42.Wrapper_ItemContent;
  _query_Label_12_0:import18.QueryList<any>;
  _query_Button_12_1:import18.QueryList<any>;
  _query_Icon_12_2:import18.QueryList<any>;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  /*private*/ _appEl_15:import3.AppElement;
  _Item_15_4:import42.Wrapper_Item;
  _ItemContent_15_5:import42.Wrapper_ItemContent;
  _query_Label_15_0:import18.QueryList<any>;
  _query_Button_15_1:import18.QueryList<any>;
  _query_Icon_15_2:import18.QueryList<any>;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  /*private*/ _appEl_18:import3.AppElement;
  _Item_18_4:import42.Wrapper_Item;
  _ItemContent_18_5:import42.Wrapper_ItemContent;
  _query_Label_18_0:import18.QueryList<any>;
  _query_Button_18_1:import18.QueryList<any>;
  _query_Icon_18_2:import18.QueryList<any>;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AccountPage1,renderType_AccountPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'padding-top','');
    this.renderer.setElementAttribute(this._el_0,'text-center','');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'img',(null as any));
    this.renderer.setElementAttribute(this._el_2,'src','http://www.gravatar.com/avatar?d=mm&s=140');
    this._text_3 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_0,'h2',(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_0,'ion-list',(null as any));
    this.renderer.setElementAttribute(this._el_7,'inset','');
    this._List_7_3 = new import41.Wrapper_List(this.parent.parentInjector.get(import23.Config),new import24.ElementRef(this._el_7),this.renderer,this.parent.parentInjector.get(import43.GestureController));
    this._text_8 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'button',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','item item-block');
    this.renderer.setElementAttribute(this._el_9,'ion-item','');
    this._appEl_9 = new import3.AppElement(9,7,this,this._el_9);
    var compView_9:any = import42.viewFactory_Item0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Item_9_4 = new import42.Wrapper_Item(this.parent.parentInjector.get(import44.Form),this.parent.parentInjector.get(import23.Config),new import24.ElementRef(this._el_9),this.renderer);
    this._ItemContent_9_5 = new import42.Wrapper_ItemContent();
    this._query_Label_9_0 = new import18.QueryList<any>();
    this._query_Button_9_1 = new import18.QueryList<any>();
    this._query_Icon_9_2 = new import18.QueryList<any>();
    this._appEl_9.initComponent(this._Item_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'Update Picture',(null as any));
    this._query_Label_9_0.reset(([] as any[]));
    this._Item_9_4.context.contentLabel = this._query_Label_9_0.first;
    compView_9.create(this._Item_9_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_10]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_11 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_7,'button',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','item item-block');
    this.renderer.setElementAttribute(this._el_12,'ion-item','');
    this._appEl_12 = new import3.AppElement(12,7,this,this._el_12);
    var compView_12:any = import42.viewFactory_Item0(this.viewUtils,this.injector(12),this._appEl_12);
    this._Item_12_4 = new import42.Wrapper_Item(this.parent.parentInjector.get(import44.Form),this.parent.parentInjector.get(import23.Config),new import24.ElementRef(this._el_12),this.renderer);
    this._ItemContent_12_5 = new import42.Wrapper_ItemContent();
    this._query_Label_12_0 = new import18.QueryList<any>();
    this._query_Button_12_1 = new import18.QueryList<any>();
    this._query_Icon_12_2 = new import18.QueryList<any>();
    this._appEl_12.initComponent(this._Item_12_4.context,([] as any[]),compView_12);
    this._text_13 = this.renderer.createText((null as any),'Change Username',(null as any));
    this._query_Label_12_0.reset(([] as any[]));
    this._Item_12_4.context.contentLabel = this._query_Label_12_0.first;
    compView_12.create(this._Item_12_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_13]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_14 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_7,'button',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','item item-block');
    this.renderer.setElementAttribute(this._el_15,'ion-item','');
    this._appEl_15 = new import3.AppElement(15,7,this,this._el_15);
    var compView_15:any = import42.viewFactory_Item0(this.viewUtils,this.injector(15),this._appEl_15);
    this._Item_15_4 = new import42.Wrapper_Item(this.parent.parentInjector.get(import44.Form),this.parent.parentInjector.get(import23.Config),new import24.ElementRef(this._el_15),this.renderer);
    this._ItemContent_15_5 = new import42.Wrapper_ItemContent();
    this._query_Label_15_0 = new import18.QueryList<any>();
    this._query_Button_15_1 = new import18.QueryList<any>();
    this._query_Icon_15_2 = new import18.QueryList<any>();
    this._appEl_15.initComponent(this._Item_15_4.context,([] as any[]),compView_15);
    this._text_16 = this.renderer.createText((null as any),'Change Password',(null as any));
    this._query_Label_15_0.reset(([] as any[]));
    this._Item_15_4.context.contentLabel = this._query_Label_15_0.first;
    compView_15.create(this._Item_15_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_16]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_17 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_7,'button',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','item item-block');
    this.renderer.setElementAttribute(this._el_18,'ion-item','');
    this._appEl_18 = new import3.AppElement(18,7,this,this._el_18);
    var compView_18:any = import42.viewFactory_Item0(this.viewUtils,this.injector(18),this._appEl_18);
    this._Item_18_4 = new import42.Wrapper_Item(this.parent.parentInjector.get(import44.Form),this.parent.parentInjector.get(import23.Config),new import24.ElementRef(this._el_18),this.renderer);
    this._ItemContent_18_5 = new import42.Wrapper_ItemContent();
    this._query_Label_18_0 = new import18.QueryList<any>();
    this._query_Button_18_1 = new import18.QueryList<any>();
    this._query_Icon_18_2 = new import18.QueryList<any>();
    this._appEl_18.initComponent(this._Item_18_4.context,([] as any[]),compView_18);
    this._text_19 = this.renderer.createText((null as any),'Logout',(null as any));
    this._query_Label_18_0.reset(([] as any[]));
    this._Item_18_4.context.contentLabel = this._query_Label_18_0.first;
    compView_18.create(this._Item_18_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_19]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_20 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._text_21 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_9,'click',this.eventHandler(this._handle_click_9_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_12,'click',this.eventHandler(this._handle_click_12_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_15,'click',this.eventHandler(this._handle_click_15_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_18,'click',this.eventHandler(this._handle_click_18_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import45.Item) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._Item_9_4.context; }
    if (((token === import45.ItemContent) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ItemContent_9_5.context; }
    if (((token === import45.Item) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Item_12_4.context; }
    if (((token === import45.ItemContent) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._ItemContent_12_5.context; }
    if (((token === import45.Item) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._Item_15_4.context; }
    if (((token === import45.ItemContent) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._ItemContent_15_5.context; }
    if (((token === import45.Item) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._Item_18_4.context; }
    if (((token === import45.ItemContent) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._ItemContent_18_5.context; }
    if (((token === import46.List) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._List_7_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._List_7_3.detectChangesInternal(this,this._el_7,throwOnChange);
    if (this._Item_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    this._ItemContent_9_5.detectChangesInternal(this,this._el_9,throwOnChange);
    if (this._Item_12_4.detectChangesInternal(this,this._el_12,throwOnChange)) { this._appEl_12.componentView.markAsCheckOnce(); }
    this._ItemContent_12_5.detectChangesInternal(this,this._el_12,throwOnChange);
    if (this._Item_15_4.detectChangesInternal(this,this._el_15,throwOnChange)) { this._appEl_15.componentView.markAsCheckOnce(); }
    this._ItemContent_15_5.detectChangesInternal(this,this._el_15,throwOnChange);
    if (this._Item_18_4.detectChangesInternal(this,this._el_18,throwOnChange)) { this._appEl_18.componentView.markAsCheckOnce(); }
    this._ItemContent_18_5.detectChangesInternal(this,this._el_18,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_9_1.dirty) {
        this._query_Button_9_1.reset(([] as any[]));
        this._Item_9_4.context._buttons = this._query_Button_9_1;
        this._query_Button_9_1.notifyOnChanges();
      }
      if (this._query_Icon_9_2.dirty) {
        this._query_Icon_9_2.reset(([] as any[]));
        this._Item_9_4.context._icons = this._query_Icon_9_2;
        this._query_Icon_9_2.notifyOnChanges();
      }
      if (this._query_Button_12_1.dirty) {
        this._query_Button_12_1.reset(([] as any[]));
        this._Item_12_4.context._buttons = this._query_Button_12_1;
        this._query_Button_12_1.notifyOnChanges();
      }
      if (this._query_Icon_12_2.dirty) {
        this._query_Icon_12_2.reset(([] as any[]));
        this._Item_12_4.context._icons = this._query_Icon_12_2;
        this._query_Icon_12_2.notifyOnChanges();
      }
      if (this._query_Button_15_1.dirty) {
        this._query_Button_15_1.reset(([] as any[]));
        this._Item_15_4.context._buttons = this._query_Button_15_1;
        this._query_Button_15_1.notifyOnChanges();
      }
      if (this._query_Icon_15_2.dirty) {
        this._query_Icon_15_2.reset(([] as any[]));
        this._Item_15_4.context._icons = this._query_Icon_15_2;
        this._query_Icon_15_2.notifyOnChanges();
      }
      if (this._query_Button_18_1.dirty) {
        this._query_Button_18_1.reset(([] as any[]));
        this._Item_18_4.context._buttons = this._query_Button_18_1;
        this._query_Button_18_1.notifyOnChanges();
      }
      if (this._query_Icon_18_2.dirty) {
        this._query_Icon_18_2.reset(([] as any[]));
        this._Item_18_4.context._icons = this._query_Icon_18_2;
        this._query_Icon_18_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_9_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_12_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_15_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_18_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = import4.interpolate(1,'',this.parent.context.username,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_5,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.updatePicture()) !== false);
    return (true && pd_0);
  }
  private _handle_click_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.changeUsername()) !== false);
    return (true && pd_0);
  }
  private _handle_click_15_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.changePassword()) !== false);
    return (true && pd_0);
  }
  private _handle_click_18_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.logout()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_AccountPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_AccountPage1(viewUtils,parentInjector,declarationEl);
}