/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './signup';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '../../providers/user-data';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/menu/menu-toggle.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import17 from '@angular/core/src/linker/query_list';
import * as import18 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import22 from '../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import23 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import24 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import25 from '../../node_modules/ionic-angular/components/label/label.ngfactory';
import * as import26 from '../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import27 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import28 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import29 from '../../node_modules/ionic-angular/components/typography/typography.ngfactory';
import * as import30 from 'ionic-angular/config/config';
import * as import31 from '@angular/core/src/linker/element_ref';
import * as import32 from 'ionic-angular/navigation/view-controller';
import * as import33 from 'ionic-angular/components/app/app';
import * as import34 from 'ionic-angular/components/menu/menu-controller';
import * as import35 from 'ionic-angular/components/toolbar/toolbar';
import * as import36 from 'ionic-angular/util/keyboard';
import * as import37 from '@angular/core/src/zone/ng_zone';
import * as import38 from 'ionic-angular/components/tabs/tabs';
import * as import39 from 'ionic-angular/gestures/gesture-controller';
import * as import40 from 'ionic-angular/util/form';
import * as import41 from 'ionic-angular/platform/platform';
import * as import42 from 'ionic-angular/components/icon/icon';
import * as import43 from 'ionic-angular/components/button/button';
import * as import44 from 'ionic-angular/components/menu/menu-toggle';
import * as import45 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import46 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import47 from 'ionic-angular/components/navbar/navbar';
import * as import48 from 'ionic-angular/components/label/label';
import * as import49 from '@angular/forms/src/directives/validators';
import * as import50 from '@angular/forms/src/validators';
import * as import51 from '@angular/forms/src/directives/ng_model';
import * as import52 from '@angular/forms/src/directives/ng_control';
import * as import53 from '@angular/forms/src/directives/ng_control_status';
import * as import54 from 'ionic-angular/components/input/input';
import * as import55 from 'ionic-angular/components/item/item';
import * as import56 from 'ionic-angular/components/typography/typography';
import * as import57 from '@angular/forms/src/directives/ng_form';
import * as import58 from '@angular/forms/src/directives/control_container';
import * as import59 from 'ionic-angular/components/list/list';
import * as import60 from 'ionic-angular/components/content/content';
export class Wrapper_SignupPage {
  context:import0.SignupPage;
  changed:boolean;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this.context = new import0.SignupPage(p0,p1);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_SignupPage_Host:import2.RenderComponentType = (null as any);
class _View_SignupPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _SignupPage_0_4:Wrapper_SignupPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SignupPage_Host0,renderType_SignupPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-login',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SignupPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SignupPage_0_4 = new Wrapper_SignupPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.UserData));
    this._appEl_0.initComponent(this._SignupPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._SignupPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.SignupPage) && (0 === requestNodeIndex))) { return this._SignupPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._SignupPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SignupPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_SignupPage_Host === (null as any))) { (renderType_SignupPage_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_SignupPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const SignupPageNgFactory:import11.ComponentFactory<import0.SignupPage> = new import11.ComponentFactory<import0.SignupPage>('page-login',viewFactory_SignupPage_Host0,import0.SignupPage);
const styles_SignupPage:any[] = ([] as any[]);
var renderType_SignupPage:import2.RenderComponentType = (null as any);
class _View_SignupPage0 extends import1.AppView<import0.SignupPage> {
  _el_0:any;
  _Header_0_3:import12.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import13.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _Button_4_4:import14.Wrapper_Button;
  _MenuToggle_4_5:import15.Wrapper_MenuToggle;
  _ToolbarItem_4_6:import16.Wrapper_ToolbarItem;
  _query_Button_4_0:import17.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import18.Wrapper_Icon;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _ToolbarTitle_9_4:import19.Wrapper_ToolbarTitle;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import3.AppElement;
  _Content_14_4:import20.Wrapper_Content;
  _text_15:any;
  _el_16:any;
  _List_16_3:import21.Wrapper_List;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _NgForm_23_3:import22.Wrapper_NgForm;
  _ControlContainer_23_4:any;
  _NgControlStatusGroup_23_5:import23.Wrapper_NgControlStatusGroup;
  _text_24:any;
  _el_25:any;
  /*private*/ _appEl_25:import3.AppElement;
  _Item_25_4:import24.Wrapper_Item;
  _ItemContent_25_5:import24.Wrapper_ItemContent;
  _query_Label_25_0:import17.QueryList<any>;
  _query_Button_25_1:import17.QueryList<any>;
  _query_Icon_25_2:import17.QueryList<any>;
  _text_26:any;
  _el_27:any;
  _Label_27_3:import25.Wrapper_Label;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  /*private*/ _appEl_30:import3.AppElement;
  _RequiredValidator_30_4:import26.Wrapper_RequiredValidator;
  _NG_VALIDATORS_30_5:any[];
  _NgModel_30_6:import27.Wrapper_NgModel;
  _NgControl_30_7:any;
  _NgControlStatus_30_8:import23.Wrapper_NgControlStatus;
  _TextInput_30_9:import28.Wrapper_TextInput;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _Typography_34_3:import29.Wrapper_Typography;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  /*private*/ _appEl_37:import3.AppElement;
  _Item_37_4:import24.Wrapper_Item;
  _ItemContent_37_5:import24.Wrapper_ItemContent;
  _query_Label_37_0:import17.QueryList<any>;
  _query_Button_37_1:import17.QueryList<any>;
  _query_Icon_37_2:import17.QueryList<any>;
  _text_38:any;
  _el_39:any;
  _Label_39_3:import25.Wrapper_Label;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  /*private*/ _appEl_42:import3.AppElement;
  _RequiredValidator_42_4:import26.Wrapper_RequiredValidator;
  _NG_VALIDATORS_42_5:any[];
  _NgModel_42_6:import27.Wrapper_NgModel;
  _NgControl_42_7:any;
  _NgControlStatus_42_8:import23.Wrapper_NgControlStatus;
  _TextInput_42_9:import28.Wrapper_TextInput;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _Typography_46_3:import29.Wrapper_Typography;
  _text_47:any;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _el_51:any;
  /*private*/ _appEl_51:import3.AppElement;
  _Button_51_4:import14.Wrapper_Button;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_41:any;
  /*private*/ _expr_42:any;
  /*private*/ _expr_44:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SignupPage0,renderType_SignupPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import12.Wrapper_Header(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import32.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import13.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import13.Wrapper_Navbar(this.parentInjector.get(import33.App),this.parentInjector.get(import32.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'ion-button','');
    this.renderer.setElementAttribute(this._el_4,'menuToggle','');
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import14.viewFactory_Button0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Button_4_4 = new import14.Wrapper_Button('','',this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_4),this.renderer);
    this._MenuToggle_4_5 = new import15.Wrapper_MenuToggle(this.parentInjector.get(import34.MenuController),new import31.ElementRef(this._el_4),this.parentInjector.get(import32.ViewController,(null as any)),this._Navbar_2_4.context);
    this._ToolbarItem_4_6 = new import16.Wrapper_ToolbarItem(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import35.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._query_Button_4_0 = new import17.QueryList<any>();
    this._appEl_4.initComponent(this._Button_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'name','menu');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._Icon_6_3 = new import18.Wrapper_Icon(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_4.create(this._Button_4_4.context,[([] as any[]).concat([
        this._text_5,
        this._el_6,
        this._text_7
      ]
    )],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_9 = new import3.AppElement(9,2,this,this._el_9);
    var compView_9:any = import19.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(9),this._appEl_9);
    this._ToolbarTitle_9_4 = new import19.Wrapper_ToolbarTitle(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import35.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_9.initComponent(this._ToolbarTitle_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'Signup',(null as any));
    compView_9.create(this._ToolbarTitle_9_4.context,[([] as any[]).concat([this._text_10])],(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]).concat([this._el_4]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_11
      ]
      )
    ]
    ,(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_14 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','login-page');
    this._appEl_14 = new import3.AppElement(14,(null as any),this,this._el_14);
    var compView_14:any = import20.viewFactory_Content0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Content_14_4 = new import20.Wrapper_Content(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import33.App),this.parentInjector.get(import36.Keyboard),this.parentInjector.get(import37.NgZone),this.parentInjector.get(import32.ViewController,(null as any)),this.parentInjector.get(import38.Tabs,(null as any)));
    this._appEl_14.initComponent(this._Content_14_4.context,([] as any[]),compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_16_3 = new import21.Wrapper_List(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_16),this.renderer,this.parentInjector.get(import39.GestureController));
    this._text_17 = this.renderer.createText(this._el_16,'\n    ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'div',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','logo');
    this._text_19 = this.renderer.createText(this._el_18,'\n      ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'img',(null as any));
    this.renderer.setElementAttribute(this._el_20,'src','assets/img/appicon.svg');
    this._text_21 = this.renderer.createText(this._el_18,'\n    ',(null as any));
    this._text_22 = this.renderer.createText(this._el_16,'\n\n    ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_16,'form',(null as any));
    this.renderer.setElementAttribute(this._el_23,'novalidate','');
    this._NgForm_23_3 = new import22.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_23_4 = this._NgForm_23_3.context;
    this._NgControlStatusGroup_23_5 = new import23.Wrapper_NgControlStatusGroup(this._ControlContainer_23_4);
    this._text_24 = this.renderer.createText(this._el_23,'\n      ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_23,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','item item-block');
    this._appEl_25 = new import3.AppElement(25,23,this,this._el_25);
    var compView_25:any = import24.viewFactory_Item0(this.viewUtils,this.injector(25),this._appEl_25);
    this._Item_25_4 = new import24.Wrapper_Item(this.parentInjector.get(import40.Form),this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_25),this.renderer);
    this._ItemContent_25_5 = new import24.Wrapper_ItemContent();
    this._query_Label_25_0 = new import17.QueryList<any>();
    this._query_Button_25_1 = new import17.QueryList<any>();
    this._query_Icon_25_2 = new import17.QueryList<any>();
    this._appEl_25.initComponent(this._Item_25_4.context,([] as any[]),compView_25);
    this._text_26 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_27 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_27,'color','primary');
    this.renderer.setElementAttribute(this._el_27,'floating','');
    this._Label_27_3 = new import25.Wrapper_Label(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_27),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'Username',(null as any));
    this._text_29 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_30 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_30,'name','username');
    this.renderer.setElementAttribute(this._el_30,'required','');
    this.renderer.setElementAttribute(this._el_30,'type','text');
    this._appEl_30 = new import3.AppElement(30,25,this,this._el_30);
    var compView_30:any = import28.viewFactory_TextInput0(this.viewUtils,this.injector(30),this._appEl_30);
    this._RequiredValidator_30_4 = new import26.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_30_5 = [this._RequiredValidator_30_4.context];
    this._NgModel_30_6 = new import27.Wrapper_NgModel(this._ControlContainer_23_4,this._NG_VALIDATORS_30_5,(null as any),(null as any));
    this._NgControl_30_7 = this._NgModel_30_6.context;
    this._NgControlStatus_30_8 = new import23.Wrapper_NgControlStatus(this._NgControl_30_7);
    this._TextInput_30_9 = new import28.Wrapper_TextInput(this.parentInjector.get(import30.Config),this.parentInjector.get(import40.Form),this._Item_25_4.context,this.parentInjector.get(import33.App),this.parentInjector.get(import41.Platform),new import31.ElementRef(this._el_30),this.renderer,this._Content_14_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_30_7);
    this._appEl_30.initComponent(this._TextInput_30_9.context,([] as any[]),compView_30);
    this._text_31 = this.renderer.createText((null as any),'\n        ',(null as any));
    compView_30.create(this._TextInput_30_9.context,([] as any[]),(null as any));
    this._text_32 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_25_0.reset([this._Label_27_3.context]);
    this._Item_25_4.context.contentLabel = this._query_Label_25_0.first;
    compView_25.create(this._Item_25_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_27]),
      ([] as any[]).concat([
        this._text_26,
        this._text_29,
        this._text_32
      ]
      ),
      ([] as any[]).concat([this._el_30]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_33 = this.renderer.createText(this._el_23,'\n      ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_23,'p',(null as any));
    this.renderer.setElementAttribute(this._el_34,'color','danger');
    this.renderer.setElementAttribute(this._el_34,'padding-left','');
    this._Typography_34_3 = new import29.Wrapper_Typography(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_34),this.renderer);
    this._text_35 = this.renderer.createText(this._el_34,'\n        Username is required\n      ',(null as any));
    this._text_36 = this.renderer.createText(this._el_23,'\n\n      ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_23,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','item item-block');
    this._appEl_37 = new import3.AppElement(37,23,this,this._el_37);
    var compView_37:any = import24.viewFactory_Item0(this.viewUtils,this.injector(37),this._appEl_37);
    this._Item_37_4 = new import24.Wrapper_Item(this.parentInjector.get(import40.Form),this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_37),this.renderer);
    this._ItemContent_37_5 = new import24.Wrapper_ItemContent();
    this._query_Label_37_0 = new import17.QueryList<any>();
    this._query_Button_37_1 = new import17.QueryList<any>();
    this._query_Icon_37_2 = new import17.QueryList<any>();
    this._appEl_37.initComponent(this._Item_37_4.context,([] as any[]),compView_37);
    this._text_38 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_39 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_39,'color','primary');
    this.renderer.setElementAttribute(this._el_39,'floating','');
    this._Label_39_3 = new import25.Wrapper_Label(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_39),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'Password',(null as any));
    this._text_41 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_42 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_42,'name','password');
    this.renderer.setElementAttribute(this._el_42,'required','');
    this.renderer.setElementAttribute(this._el_42,'type','password');
    this._appEl_42 = new import3.AppElement(42,37,this,this._el_42);
    var compView_42:any = import28.viewFactory_TextInput0(this.viewUtils,this.injector(42),this._appEl_42);
    this._RequiredValidator_42_4 = new import26.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_42_5 = [this._RequiredValidator_42_4.context];
    this._NgModel_42_6 = new import27.Wrapper_NgModel(this._ControlContainer_23_4,this._NG_VALIDATORS_42_5,(null as any),(null as any));
    this._NgControl_42_7 = this._NgModel_42_6.context;
    this._NgControlStatus_42_8 = new import23.Wrapper_NgControlStatus(this._NgControl_42_7);
    this._TextInput_42_9 = new import28.Wrapper_TextInput(this.parentInjector.get(import30.Config),this.parentInjector.get(import40.Form),this._Item_37_4.context,this.parentInjector.get(import33.App),this.parentInjector.get(import41.Platform),new import31.ElementRef(this._el_42),this.renderer,this._Content_14_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_42_7);
    this._appEl_42.initComponent(this._TextInput_42_9.context,([] as any[]),compView_42);
    this._text_43 = this.renderer.createText((null as any),'\n        ',(null as any));
    compView_42.create(this._TextInput_42_9.context,([] as any[]),(null as any));
    this._text_44 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_37_0.reset([this._Label_39_3.context]);
    this._Item_37_4.context.contentLabel = this._query_Label_37_0.first;
    compView_37.create(this._Item_37_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_39]),
      ([] as any[]).concat([
        this._text_38,
        this._text_41,
        this._text_44
      ]
      ),
      ([] as any[]).concat([this._el_42]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_45 = this.renderer.createText(this._el_23,'\n      ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_23,'p',(null as any));
    this.renderer.setElementAttribute(this._el_46,'color','danger');
    this.renderer.setElementAttribute(this._el_46,'padding-left','');
    this._Typography_46_3 = new import29.Wrapper_Typography(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_46),this.renderer);
    this._text_47 = this.renderer.createText(this._el_46,'\n        Password is required\n      ',(null as any));
    this._text_48 = this.renderer.createText(this._el_23,'\n\n      ',(null as any));
    this._el_49 = this.renderer.createElement(this._el_23,'div',(null as any));
    this.renderer.setElementAttribute(this._el_49,'padding','');
    this._text_50 = this.renderer.createText(this._el_49,'\n        ',(null as any));
    this._el_51 = this.renderer.createElement(this._el_49,'button',(null as any));
    this.renderer.setElementAttribute(this._el_51,'block','');
    this.renderer.setElementAttribute(this._el_51,'color','primary');
    this.renderer.setElementAttribute(this._el_51,'ion-button','');
    this.renderer.setElementAttribute(this._el_51,'type','submit');
    this._appEl_51 = new import3.AppElement(51,49,this,this._el_51);
    var compView_51:any = import14.viewFactory_Button0(this.viewUtils,this.injector(51),this._appEl_51);
    this._Button_51_4 = new import14.Wrapper_Button((null as any),'',this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_51),this.renderer);
    this._appEl_51.initComponent(this._Button_51_4.context,([] as any[]),compView_51);
    this._text_52 = this.renderer.createText((null as any),'Create',(null as any));
    compView_51.create(this._Button_51_4.context,[([] as any[]).concat([this._text_52])],(null as any));
    this._text_53 = this.renderer.createText(this._el_49,'\n      ',(null as any));
    this._text_54 = this.renderer.createText(this._el_23,'\n    ',(null as any));
    this._text_55 = this.renderer.createText(this._el_16,'\n  ',(null as any));
    this._text_56 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_14.create(this._Content_14_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_15,
        this._el_16,
        this._text_56
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_57 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_23,'submit',this.eventHandler(this._handle_submit_23_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_23,'reset',this.eventHandler(this._handle_reset_23_1.bind(this)));
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_30,'ngModelChange',this.eventHandler(this._handle_ngModelChange_30_0.bind(this)));
    this._expr_19 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_30_6.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_30_0.bind(this)));
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_42,'ngModelChange',this.eventHandler(this._handle_ngModelChange_42_0.bind(this)));
    this._expr_34 = import7.UNINITIALIZED;
    const subscription_1:any = this._NgModel_42_6.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_42_0.bind(this)));
    this._expr_37 = import7.UNINITIALIZED;
    this._expr_38 = import7.UNINITIALIZED;
    this._expr_39 = import7.UNINITIALIZED;
    this._expr_40 = import7.UNINITIALIZED;
    this._expr_41 = import7.UNINITIALIZED;
    this._expr_42 = import7.UNINITIALIZED;
    this._expr_44 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_51,'click',this.eventHandler(this._handle_click_51_0.bind(this)));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._text_56,
      this._text_57
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import42.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3.context; }
    if (((token === import43.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_4_4.context; }
    if (((token === import44.MenuToggle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._MenuToggle_4_5.context; }
    if (((token === import45.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarItem_4_6.context; }
    if (((token === import46.ToolbarTitle) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarTitle_9_4.context; }
    if (((token === import47.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Navbar_2_4.context; }
    if (((token === import35.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Header_0_3.context; }
    if (((token === import48.Label) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Label_27_3.context; }
    if (((token === import49.RequiredValidator) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._RequiredValidator_30_4.context; }
    if (((token === import50.NG_VALIDATORS) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._NG_VALIDATORS_30_5; }
    if (((token === import51.NgModel) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._NgModel_30_6.context; }
    if (((token === import52.NgControl) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._NgControl_30_7; }
    if (((token === import53.NgControlStatus) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._NgControlStatus_30_8.context; }
    if (((token === import54.TextInput) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._TextInput_30_9.context; }
    if (((token === import55.Item) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._Item_25_4.context; }
    if (((token === import55.ItemContent) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._ItemContent_25_5.context; }
    if (((token === import56.Typography) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._Typography_34_3.context; }
    if (((token === import48.Label) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._Label_39_3.context; }
    if (((token === import49.RequiredValidator) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._RequiredValidator_42_4.context; }
    if (((token === import50.NG_VALIDATORS) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._NG_VALIDATORS_42_5; }
    if (((token === import51.NgModel) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._NgModel_42_6.context; }
    if (((token === import52.NgControl) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._NgControl_42_7; }
    if (((token === import53.NgControlStatus) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._NgControlStatus_42_8.context; }
    if (((token === import54.TextInput) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._TextInput_42_9.context; }
    if (((token === import55.Item) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._Item_37_4.context; }
    if (((token === import55.ItemContent) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._ItemContent_37_5.context; }
    if (((token === import56.Typography) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._Typography_46_3.context; }
    if (((token === import43.Button) && ((51 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._Button_51_4.context; }
    if (((token === import57.NgForm) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 54)))) { return this._NgForm_23_3.context; }
    if (((token === import58.ControlContainer) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 54)))) { return this._ControlContainer_23_4; }
    if (((token === import53.NgControlStatusGroup) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 54)))) { return this._NgControlStatusGroup_23_5.context; }
    if (((token === import59.List) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 55)))) { return this._List_16_3.context; }
    if (((token === import60.Content) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._Content_14_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._Button_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    const currVal_3:any = '';
    this._MenuToggle_4_5.check_menuToggle(currVal_3,throwOnChange,false);
    this._MenuToggle_4_5.detectChangesInternal(this,this._el_4,throwOnChange);
    this._ToolbarItem_4_6.detectChangesInternal(this,this._el_4,throwOnChange);
    const currVal_5:any = 'menu';
    this._Icon_6_3.check_name(currVal_5,throwOnChange,false);
    this._Icon_6_3.detectChangesInternal(this,this._el_6,throwOnChange);
    if (this._ToolbarTitle_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    if (this._Content_14_4.detectChangesInternal(this,this._el_14,throwOnChange)) { this._appEl_14.componentView.markAsCheckOnce(); }
    this._List_16_3.detectChangesInternal(this,this._el_16,throwOnChange);
    this._NgForm_23_3.detectChangesInternal(this,this._el_23,throwOnChange);
    this._NgControlStatusGroup_23_5.detectChangesInternal(this,this._el_23,throwOnChange);
    if (this._Item_25_4.detectChangesInternal(this,this._el_25,throwOnChange)) { this._appEl_25.componentView.markAsCheckOnce(); }
    this._ItemContent_25_5.detectChangesInternal(this,this._el_25,throwOnChange);
    const currVal_16:any = 'primary';
    this._Label_27_3.check_color(currVal_16,throwOnChange,false);
    this._Label_27_3.detectChangesInternal(this,this._el_27,throwOnChange);
    const currVal_18:any = '';
    this._RequiredValidator_30_4.check_required(currVal_18,throwOnChange,false);
    this._RequiredValidator_30_4.detectChangesInternal(this,this._el_30,throwOnChange);
    const currVal_20:any = 'username';
    this._NgModel_30_6.check_name(currVal_20,throwOnChange,false);
    const currVal_21:any = this.context.signup.username;
    this._NgModel_30_6.check_model(currVal_21,throwOnChange,false);
    this._NgModel_30_6.detectChangesInternal(this,this._el_30,throwOnChange);
    this._NgControlStatus_30_8.detectChangesInternal(this,this._el_30,throwOnChange);
    const currVal_28:any = 'text';
    this._TextInput_30_9.check_type(currVal_28,throwOnChange,false);
    this._TextInput_30_9.detectChangesInternal(this,this._el_30,throwOnChange);
    const currVal_30:any = 'danger';
    this._Typography_34_3.check_color(currVal_30,throwOnChange,false);
    this._Typography_34_3.detectChangesInternal(this,this._el_34,throwOnChange);
    if (this._Item_37_4.detectChangesInternal(this,this._el_37,throwOnChange)) { this._appEl_37.componentView.markAsCheckOnce(); }
    this._ItemContent_37_5.detectChangesInternal(this,this._el_37,throwOnChange);
    const currVal_31:any = 'primary';
    this._Label_39_3.check_color(currVal_31,throwOnChange,false);
    this._Label_39_3.detectChangesInternal(this,this._el_39,throwOnChange);
    const currVal_33:any = '';
    this._RequiredValidator_42_4.check_required(currVal_33,throwOnChange,false);
    this._RequiredValidator_42_4.detectChangesInternal(this,this._el_42,throwOnChange);
    const currVal_35:any = 'password';
    this._NgModel_42_6.check_name(currVal_35,throwOnChange,false);
    const currVal_36:any = this.context.signup.password;
    this._NgModel_42_6.check_model(currVal_36,throwOnChange,false);
    this._NgModel_42_6.detectChangesInternal(this,this._el_42,throwOnChange);
    this._NgControlStatus_42_8.detectChangesInternal(this,this._el_42,throwOnChange);
    const currVal_43:any = 'password';
    this._TextInput_42_9.check_type(currVal_43,throwOnChange,false);
    this._TextInput_42_9.detectChangesInternal(this,this._el_42,throwOnChange);
    const currVal_45:any = 'danger';
    this._Typography_46_3.check_color(currVal_45,throwOnChange,false);
    this._Typography_46_3.detectChangesInternal(this,this._el_46,throwOnChange);
    const currVal_47:any = '';
    this._Button_51_4.check_block(currVal_47,throwOnChange,false);
    const currVal_48:any = 'primary';
    this._Button_51_4.check_color(currVal_48,throwOnChange,false);
    if (this._Button_51_4.detectChangesInternal(this,this._el_51,throwOnChange)) { this._appEl_51.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_4_4.context]);
        this._ToolbarItem_4_6.context._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if (this._query_Button_25_1.dirty) {
        this._query_Button_25_1.reset(([] as any[]));
        this._Item_25_4.context._buttons = this._query_Button_25_1;
        this._query_Button_25_1.notifyOnChanges();
      }
      if (this._query_Icon_25_2.dirty) {
        this._query_Icon_25_2.reset(([] as any[]));
        this._Item_25_4.context._icons = this._query_Icon_25_2;
        this._query_Icon_25_2.notifyOnChanges();
      }
      if (this._query_Button_37_1.dirty) {
        this._query_Button_37_1.reset(([] as any[]));
        this._Item_37_4.context._buttons = this._query_Button_37_1;
        this._query_Button_37_1.notifyOnChanges();
      }
      if (this._query_Icon_37_2.dirty) {
        this._query_Icon_37_2.reset(([] as any[]));
        this._Item_37_4.context._icons = this._query_Icon_37_2;
        this._query_Icon_37_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_4_4.context.ngAfterContentInit(); }
      this._TextInput_30_9.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_25_4.context.ngAfterContentInit(); }
      this._TextInput_42_9.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_37_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_51_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_4_5.context.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_4,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_6_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._Content_14_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_14,'statusbar-padding',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_10:any = this._NgControlStatusGroup_23_5.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_23,'ng-untouched',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatusGroup_23_5.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_23,'ng-touched',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatusGroup_23_5.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_23,'ng-pristine',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatusGroup_23_5.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_23,'ng-dirty',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._NgControlStatusGroup_23_5.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_23,'ng-valid',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatusGroup_23_5.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_23,'ng-invalid',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_19:any = (this._RequiredValidator_30_4.context.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementAttribute(this._el_30,'required',((currVal_19 == (null as any))? (null as any): currVal_19.toString()));
      this._expr_19 = currVal_19;
    }
    const currVal_22:any = this._NgControlStatus_30_8.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_30,'ng-untouched',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this._NgControlStatus_30_8.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_30,'ng-touched',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this._NgControlStatus_30_8.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_30,'ng-pristine',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = this._NgControlStatus_30_8.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_30,'ng-dirty',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._NgControlStatus_30_8.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_30,'ng-valid',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._NgControlStatus_30_8.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_30,'ng-invalid',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_29:any = (this._NgModel_30_6.context.valid || (this.context.submitted == false));
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementProperty(this._el_34,'hidden',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_34:any = (this._RequiredValidator_42_4.context.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementAttribute(this._el_42,'required',((currVal_34 == (null as any))? (null as any): currVal_34.toString()));
      this._expr_34 = currVal_34;
    }
    const currVal_37:any = this._NgControlStatus_42_8.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementClass(this._el_42,'ng-untouched',currVal_37);
      this._expr_37 = currVal_37;
    }
    const currVal_38:any = this._NgControlStatus_42_8.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this.renderer.setElementClass(this._el_42,'ng-touched',currVal_38);
      this._expr_38 = currVal_38;
    }
    const currVal_39:any = this._NgControlStatus_42_8.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementClass(this._el_42,'ng-pristine',currVal_39);
      this._expr_39 = currVal_39;
    }
    const currVal_40:any = this._NgControlStatus_42_8.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this.renderer.setElementClass(this._el_42,'ng-dirty',currVal_40);
      this._expr_40 = currVal_40;
    }
    const currVal_41:any = this._NgControlStatus_42_8.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_41,currVal_41)) {
      this.renderer.setElementClass(this._el_42,'ng-valid',currVal_41);
      this._expr_41 = currVal_41;
    }
    const currVal_42:any = this._NgControlStatus_42_8.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this.renderer.setElementClass(this._el_42,'ng-invalid',currVal_42);
      this._expr_42 = currVal_42;
    }
    const currVal_44:any = (this._NgModel_42_6.context.valid || (this.context.submitted == false));
    if (import4.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setElementProperty(this._el_46,'hidden',currVal_44);
      this._expr_44 = currVal_44;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_6_3.context.ngOnDestroy();
    this._NgModel_30_6.context.ngOnDestroy();
    this._TextInput_30_9.context.ngOnDestroy();
    this._NgModel_42_6.context.ngOnDestroy();
    this._TextInput_42_9.context.ngOnDestroy();
    this._Content_14_4.context.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_4_5.context.toggle()) !== false);
    return (true && pd_0);
  }
  private _handle_submit_23_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_23_3.context.onSubmit($event)) !== false);
    return (true && pd_0);
  }
  private _handle_reset_23_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_23_3.context.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_30_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.signup.username = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_42_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.signup.password = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_51_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onSignup(this._NgForm_23_3.context)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_SignupPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.SignupPage> {
  if ((renderType_SignupPage === (null as any))) { (renderType_SignupPage = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,styles_SignupPage,{})); }
  return new _View_SignupPage0(viewUtils,parentInjector,declarationEl);
}